/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagLowercasePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  caseStrategy: "lowercase",
  separatorStrategy: "preserve",
  removeSpecialChars: false,
  applyToNestedTags: true,
  tagFormat: "inline",
  aliases: {},
  operationHistory: [],
  scopeFilter: {
    enabled: false,
    includeFolders: [],
    excludeFolders: [],
    filePattern: ""
  },
  orphanThreshold: 2,
  maxHistorySize: 50
};
var TAG_REGEX = /(^|\s)(#[\p{L}\p{N}_\-\/]+)/gu;
var TagLowercasePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.aliasDebounceTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("tags", "Bulk Tag Manager", () => {
      new TagManagerModal(this.app, this).open();
    });
    this.addCommand({
      id: "open-tag-manager",
      name: "Open Tag Manager Dashboard",
      callback: () => new TagManagerModal(this.app, this).open()
    });
    this.addCommand({
      id: "convert-all-tags",
      name: "Convert all tags (with preview)",
      callback: () => this.runConversionWithPreview()
    });
    this.addCommand({
      id: "generate-tag-list",
      name: "Generate Tag List",
      callback: () => this.generateTagList()
    });
    this.addCommand({
      id: "show-tag-hierarchy",
      name: "Show Tag Hierarchy",
      callback: () => new TagHierarchyModal(this.app, this).open()
    });
    this.addCommand({
      id: "find-orphan-tags",
      name: "Find Orphaned Tags",
      callback: () => new OrphanTagsModal(this.app, this).open()
    });
    this.addCommand({
      id: "undo-last-operation",
      name: "Undo Last Tag Operation",
      callback: () => this.undoLastOperation()
    });
    this.addSettingTab(new TagLowercaseSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile && Object.keys(this.settings.aliases).length > 0) {
          this.applyAliasesDebounced(file);
        }
      })
    );
  }
  applyAliasesDebounced(file) {
    if (this.aliasDebounceTimer) clearTimeout(this.aliasDebounceTimer);
    this.aliasDebounceTimer = setTimeout(() => this.applyAliases(file), 1e3);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // --- File Filtering ---
  getFilteredFiles() {
    let files = this.app.vault.getMarkdownFiles();
    if (!this.settings.scopeFilter.enabled) return files;
    const { includeFolders, excludeFolders, filePattern } = this.settings.scopeFilter;
    if (includeFolders.length > 0) {
      files = files.filter((f) => includeFolders.some((folder) => f.path.startsWith(folder)));
    }
    if (excludeFolders.length > 0) {
      files = files.filter((f) => !excludeFolders.some((folder) => f.path.startsWith(folder)));
    }
    if (filePattern) {
      try {
        const regex = new RegExp(filePattern);
        files = files.filter((f) => regex.test(f.path));
      } catch (e) {
      }
    }
    return files;
  }
  // --- History Management ---
  async addToHistory(record) {
    const fullRecord = {
      ...record,
      id: crypto.randomUUID(),
      timestamp: Date.now()
    };
    this.settings.operationHistory.unshift(fullRecord);
    if (this.settings.operationHistory.length > this.settings.maxHistorySize) {
      this.settings.operationHistory = this.settings.operationHistory.slice(0, this.settings.maxHistorySize);
    }
    await this.saveSettings();
  }
  async undoLastOperation() {
    if (this.settings.operationHistory.length === 0) {
      new import_obsidian.Notice("No operations to undo.");
      return;
    }
    const lastOp = this.settings.operationHistory[0];
    let revertedCount = 0;
    new import_obsidian.Notice(`Reverting: ${lastOp.description}...`);
    for (const change of lastOp.changes) {
      const file = this.app.vault.getAbstractFileByPath(change.path);
      if (file instanceof import_obsidian.TFile) {
        try {
          await this.app.vault.modify(file, change.before);
          revertedCount++;
        } catch (e) {
          console.error(`Failed to revert ${change.path}:`, e);
        }
      }
    }
    this.settings.operationHistory.shift();
    await this.saveSettings();
    new import_obsidian.Notice(`Reverted ${revertedCount} files.`);
  }
  // --- Preview System ---
  async previewConversion() {
    const files = this.getFilteredFiles();
    const affectedFiles = [];
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const newContent = this.transformContent(content);
      if (content !== newContent) {
        const changes = this.diffContent(content, newContent);
        affectedFiles.push({ path: file.path, changes, included: true });
      }
    }
    return {
      affectedFiles,
      totalChanges: affectedFiles.reduce((sum, f) => sum + f.changes.length, 0)
    };
  }
  diffContent(before, after) {
    const beforeLines = before.split("\n");
    const afterLines = after.split("\n");
    const changes = [];
    for (let i = 0; i < Math.max(beforeLines.length, afterLines.length); i++) {
      if (beforeLines[i] !== afterLines[i]) {
        changes.push({ line: i + 1, before: beforeLines[i] || "", after: afterLines[i] || "" });
      }
    }
    return changes;
  }
  transformContent(content) {
    const codeBlockRegex = /```[\s\S]*?```|`[^`\n]+`/g;
    const codeBlocks = [];
    let match;
    while ((match = codeBlockRegex.exec(content)) !== null) {
      codeBlocks.push({ start: match.index, end: match.index + match[0].length });
    }
    return content.replace(TAG_REGEX, (fullMatch, prefix, tag, offset) => {
      if (codeBlocks.some((b) => offset >= b.start && offset < b.end)) {
        return fullMatch;
      }
      const clean = tag.substring(1);
      const converted = this.convertTagContent(clean);
      return prefix + "#" + converted;
    });
  }
  async runConversionWithPreview() {
    const preview = await this.previewConversion();
    if (preview.affectedFiles.length === 0) {
      new import_obsidian.Notice("No tags need conversion.");
      return;
    }
    new PreviewModal(this.app, this, preview, async (selectedFiles) => {
      await this.executeConversion(selectedFiles);
    }).open();
  }
  async executeConversion(files) {
    const changes = [];
    let processedCount = 0;
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    for (const previewFile of files) {
      if (!previewFile.included) continue;
      const file = this.app.vault.getAbstractFileByPath(previewFile.path);
      if (!(file instanceof import_obsidian.TFile)) continue;
      try {
        const before = await this.app.vault.read(file);
        await this.processFile(file);
        const after = await this.app.vault.read(file);
        if (before !== after) {
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "convert",
        description: `Bulk conversion (${changes.length} files)`,
        changes
      });
    }
    new import_obsidian.Notice(`Converted tags in ${processedCount} files.`);
  }
  // --- Tag Operations ---
  async runConversion() {
    const files = this.getFilteredFiles();
    const changes = [];
    let processedCount = 0;
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    for (const file of files) {
      try {
        const before = await this.app.vault.read(file);
        await this.processFile(file);
        const after = await this.app.vault.read(file);
        if (before !== after) {
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "convert",
        description: `Bulk conversion (${changes.length} files)`,
        changes
      });
    }
    new import_obsidian.Notice(`Processed ${processedCount} files.`);
  }
  async generateTagList() {
    const tags = this.app.metadataCache.getTags();
    if (!tags || Object.keys(tags).length === 0) {
      new import_obsidian.Notice("No tags found in vault.");
      return;
    }
    const sortedTags = Object.keys(tags).sort((a, b) => a.localeCompare(b));
    const fileContent = `# All Tags

${sortedTags.join("\n")}
`;
    const fileName = "All Tags.md";
    try {
      const existingFile = this.app.vault.getAbstractFileByPath(fileName);
      if (existingFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingFile, fileContent);
      } else {
        await this.app.vault.create(fileName, fileContent);
      }
      new import_obsidian.Notice(`Created "${fileName}" with ${sortedTags.length} tags.`);
    } catch (e) {
      console.error("Failed to create tag list:", e);
      new import_obsidian.Notice("Failed to create tag list file.");
    }
  }
  async renameTag(oldTag, newTag) {
    var _a, _b;
    const files = this.getFilteredFiles();
    const changes = [];
    const search = oldTag.startsWith("#") ? oldTag.substring(1) : oldTag;
    const replace = newTag.startsWith("#") ? newTag.substring(1) : newTag;
    if (!search || !replace) {
      new import_obsidian.Notice("Please provide both old and new tags.");
      return;
    }
    new import_obsidian.Notice(`Scanning for #${search}...`);
    const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const escapedSearch = escapeRegExp(search);
    const tagRegex = new RegExp(`(^|\\s)(#)(${escapedSearch})(?=[\\s\\/]|$|[^\\p{L}\\p{N}_-])`, "gu");
    const matchingFiles = [];
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const cache = this.app.metadataCache.getFileCache(file);
      let hasFrontmatterTag = false;
      if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) {
        const fmTags = Array.isArray(cache.frontmatter.tags) ? cache.frontmatter.tags : [cache.frontmatter.tags];
        hasFrontmatterTag = fmTags.some((t) => {
          const raw = t.startsWith("#") ? t.substring(1) : t;
          return raw === search || raw.startsWith(search + "/");
        });
      }
      if ((_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.tag) {
        const fmTags = Array.isArray(cache.frontmatter.tag) ? cache.frontmatter.tag : [cache.frontmatter.tag];
        hasFrontmatterTag = hasFrontmatterTag || fmTags.some((t) => {
          const raw = t.startsWith("#") ? t.substring(1) : t;
          return raw === search || raw.startsWith(search + "/");
        });
      }
      const hasInlineTag = tagRegex.test(content);
      tagRegex.lastIndex = 0;
      if (hasFrontmatterTag || hasInlineTag) {
        matchingFiles.push(file);
      }
    }
    if (matchingFiles.length === 0) {
      new import_obsidian.Notice(`No files found containing #${search}`);
      return;
    }
    new import_obsidian.Notice(`Found ${matchingFiles.length} files with #${search}. Renaming...`);
    const progressModal = new ProgressModal(this.app, matchingFiles.length);
    progressModal.open();
    let processedCount = 0;
    for (const file of matchingFiles) {
      try {
        const before = await this.app.vault.read(file);
        let modified = false;
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          const processSingleTag = (t) => {
            const hasHash = t.startsWith("#");
            const raw = hasHash ? t.substring(1) : t;
            if (raw === search) {
              modified = true;
              return hasHash ? "#" + replace : replace;
            } else if (raw.startsWith(search + "/")) {
              modified = true;
              const newRaw = replace + raw.substring(search.length);
              return hasHash ? "#" + newRaw : newRaw;
            }
            return t;
          };
          if (fm.tags) {
            if (Array.isArray(fm.tags)) {
              fm.tags = fm.tags.map(processSingleTag);
            } else if (typeof fm.tags === "string") {
              fm.tags = processSingleTag(fm.tags);
            }
          }
          if (fm.tag) {
            if (Array.isArray(fm.tag)) {
              fm.tag = fm.tag.map(processSingleTag);
            } else if (typeof fm.tag === "string") {
              fm.tag = processSingleTag(fm.tag);
            }
          }
        });
        await this.app.vault.process(file, (data) => {
          const newData = data.replace(tagRegex, (m, prefix, hash) => {
            modified = true;
            return prefix + hash + replace;
          });
          tagRegex.lastIndex = 0;
          return newData;
        });
        if (modified) {
          const after = await this.app.vault.read(file);
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
        processedCount++;
        progressModal.update(processedCount);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "rename",
        description: `Rename #${search} \u2192 #${replace}`,
        changes
      });
    }
    new import_obsidian.Notice(`Renamed #${search} \u2192 #${replace} in ${changes.length} files.`);
  }
  async mergeTags(sources, target) {
    const targetClean = target.startsWith("#") ? target.substring(1) : target;
    const sourcesClean = sources.map((s) => s.startsWith("#") ? s.substring(1) : s).filter((s) => s && s !== targetClean);
    if (sourcesClean.length === 0) {
      new import_obsidian.Notice("No valid source tags to merge.");
      return;
    }
    new import_obsidian.Notice(`Merging ${sourcesClean.length} tags into #${targetClean}...`);
    const files = this.getFilteredFiles();
    const changes = [];
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    let processedCount = 0;
    const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const sourcePatterns = sourcesClean.map((s) => escapeRegExp(s)).join("|");
    const tagRegex = new RegExp(`(^|\\s)(#)(${sourcePatterns})(?=[\\s\\/]|$|[^\\p{L}\\p{N}_-])`, "gu");
    for (const file of files) {
      try {
        const before = await this.app.vault.read(file);
        let modified = false;
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          const processSingleTag = (t) => {
            const hasHash = t.startsWith("#");
            const raw = hasHash ? t.substring(1) : t;
            for (const source of sourcesClean) {
              if (raw === source) {
                modified = true;
                return hasHash ? "#" + targetClean : targetClean;
              }
              if (raw.startsWith(source + "/")) {
                modified = true;
                const newRaw = targetClean + raw.substring(source.length);
                return hasHash ? "#" + newRaw : newRaw;
              }
            }
            return t;
          };
          if (fm.tags) {
            if (Array.isArray(fm.tags)) {
              fm.tags = fm.tags.map(processSingleTag);
            } else if (typeof fm.tags === "string") {
              fm.tags = processSingleTag(fm.tags);
            }
          }
          if (fm.tag) {
            if (Array.isArray(fm.tag)) {
              fm.tag = fm.tag.map(processSingleTag);
            } else if (typeof fm.tag === "string") {
              fm.tag = processSingleTag(fm.tag);
            }
          }
        });
        await this.app.vault.process(file, (data) => {
          const newData = data.replace(tagRegex, (match, prefix, hash, capturedTag) => {
            for (const source of sourcesClean) {
              if (capturedTag === source || capturedTag.startsWith(source + "/")) {
                modified = true;
                if (capturedTag === source) {
                  return prefix + hash + targetClean;
                } else {
                  return prefix + hash + targetClean + capturedTag.substring(source.length);
                }
              }
            }
            return match;
          });
          tagRegex.lastIndex = 0;
          return newData;
        });
        if (modified) {
          const after = await this.app.vault.read(file);
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
        processedCount++;
        progressModal.update(processedCount);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "merge",
        description: `Merge ${sourcesClean.map((s) => "#" + s).join(", ")} \u2192 #${targetClean}`,
        changes
      });
    }
    new import_obsidian.Notice(`Merged ${sourcesClean.length} tags into #${targetClean}. ${changes.length} files changed.`);
  }
  async batchRename(pattern, replacement) {
    const files = this.getFilteredFiles();
    const changes = [];
    let regex;
    try {
      regex = new RegExp(pattern, "g");
    } catch (e) {
      new import_obsidian.Notice("Invalid regex pattern.");
      return;
    }
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    let processedCount = 0;
    for (const file of files) {
      const before = await this.app.vault.read(file);
      await this.app.vault.process(file, (data) => {
        return data.replace(TAG_REGEX, (fullMatch, prefix, tag) => {
          const clean = tag.substring(1);
          const newTag = clean.replace(regex, replacement);
          if (newTag !== clean) {
            return prefix + "#" + newTag;
          }
          return fullMatch;
        });
      });
      const after = await this.app.vault.read(file);
      if (before !== after) {
        changes.push({ path: file.path, before, after });
      }
      processedCount++;
      progressModal.update(processedCount);
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "pattern",
        description: `Pattern: /${pattern}/ \u2192 ${replacement}`,
        changes
      });
    }
    new import_obsidian.Notice(`Pattern rename affected ${changes.length} files.`);
  }
  // --- Tag Analysis ---
  getTagHierarchy() {
    const tags = this.app.metadataCache.getTags() || {};
    const root = [];
    for (const [tag, count] of Object.entries(tags)) {
      const parts = tag.substring(1).split("/");
      let currentLevel = root;
      let currentPath = "";
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        currentPath = currentPath ? `${currentPath}/${part}` : part;
        let existingNode = currentLevel.find((n) => n.name === part);
        if (!existingNode) {
          existingNode = { name: part, fullPath: currentPath, count: 0, children: [] };
          currentLevel.push(existingNode);
        }
        if (i === parts.length - 1) {
          existingNode.count = count;
        }
        currentLevel = existingNode.children;
      }
    }
    return root;
  }
  findOrphanedTags() {
    const tags = this.app.metadataCache.getTags() || {};
    return Object.entries(tags).filter(([, count]) => count < this.settings.orphanThreshold).map(([tag, count]) => ({ tag, count })).sort((a, b) => a.count - b.count);
  }
  analyzeTagStandardization(files) {
    const tags = Object.keys(this.app.metadataCache.getTags() || {});
    const totalTags = tags.length;
    const stats = {
      totalTags,
      caseStats: { lowercase: [], uppercase: [], mixed: [], consistency: 100 },
      separatorStats: { underscore: [], hyphen: [], both: [], none: [], consistency: 100 },
      specialCharStats: { withSpecial: [], clean: [], consistency: 100 },
      nestingStats: { nested: [], flat: [], maxDepth: 0 },
      lengthStats: { short: [], medium: [], long: [], avgLength: 0 },
      locationStats: { frontmatter: [], body: [] },
      inlineFiles: [],
      nestedFiles: []
    };
    if (totalTags === 0) return stats;
    let totalLength = 0;
    for (const tag of tags) {
      const rawTag = tag.startsWith("#") ? tag.substring(1) : tag;
      const letters = rawTag.replace(/[^a-zA-Z]/g, "");
      if (letters.length > 0) {
        const isAllLower = letters === letters.toLowerCase();
        const isAllUpper = letters === letters.toUpperCase();
        if (isAllLower && !isAllUpper) stats.caseStats.lowercase.push(tag);
        else if (isAllUpper && !isAllLower) stats.caseStats.uppercase.push(tag);
        else stats.caseStats.mixed.push(tag);
      } else {
        stats.caseStats.lowercase.push(tag);
      }
      const hasUnderscore = rawTag.includes("_");
      const hasHyphen = rawTag.includes("-");
      if (hasUnderscore && hasHyphen) stats.separatorStats.both.push(tag);
      else if (hasUnderscore) stats.separatorStats.underscore.push(tag);
      else if (hasHyphen) stats.separatorStats.hyphen.push(tag);
      else stats.separatorStats.none.push(tag);
      const hasSpecial = /[^a-zA-Z0-9_\-\/]/.test(rawTag);
      if (hasSpecial) stats.specialCharStats.withSpecial.push(tag);
      else stats.specialCharStats.clean.push(tag);
      const depth = (rawTag.match(/\//g) || []).length + 1;
      if (depth > 1) stats.nestingStats.nested.push(tag);
      else stats.nestingStats.flat.push(tag);
      stats.nestingStats.maxDepth = Math.max(stats.nestingStats.maxDepth, depth);
      totalLength += rawTag.length;
      if (rawTag.length <= 10) stats.lengthStats.short.push(tag);
      else if (rawTag.length <= 25) stats.lengthStats.medium.push(tag);
      else stats.lengthStats.long.push(tag);
    }
    const fmTags = /* @__PURE__ */ new Set();
    const bodyTags = /* @__PURE__ */ new Set();
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (!cache) continue;
      const fileInlineSet = /* @__PURE__ */ new Set();
      const fileNestedSet = /* @__PURE__ */ new Set();
      const fm = cache.frontmatter;
      if (fm) {
        let list = [];
        if (fm.tags) {
          if (typeof fm.tags === "string") list = fm.tags.split(",").map((t) => t.trim());
          else if (Array.isArray(fm.tags)) list = fm.tags.map((t) => String(t));
        }
        if (fm.tag) {
          if (typeof fm.tag === "string") list = list.concat([fm.tag]);
          else if (Array.isArray(fm.tag)) list = list.concat(fm.tag.map((t) => String(t)));
        }
        list.forEach((t) => {
          const clean = t.startsWith("#") ? t.substring(1) : t;
          fmTags.add(clean);
          if (clean.includes("/")) fileNestedSet.add(clean);
        });
      }
      if (cache.tags) {
        cache.tags.forEach((t) => {
          const clean = t.tag.startsWith("#") ? t.tag.substring(1) : t.tag;
          bodyTags.add(clean);
          fileInlineSet.add(clean);
          if (clean.includes("/")) fileNestedSet.add(clean);
        });
      }
      if (fileInlineSet.size > 0) {
        stats.inlineFiles.push({
          file,
          count: fileInlineSet.size,
          tags: Array.from(fileInlineSet).sort()
        });
      }
      if (fileNestedSet.size > 0) {
        stats.nestedFiles.push({
          file,
          count: fileNestedSet.size,
          tags: Array.from(fileNestedSet).sort()
        });
      }
    }
    stats.locationStats.frontmatter = Array.from(fmTags).sort();
    stats.locationStats.body = Array.from(bodyTags).sort();
    stats.lengthStats.avgLength = Math.round(totalLength / totalTags);
    const calcConsistency = (arrays) => {
      const dominant = Math.max(...arrays.map((a) => a.length));
      return Math.round(dominant / totalTags * 100);
    };
    stats.caseStats.consistency = calcConsistency([stats.caseStats.lowercase, stats.caseStats.uppercase, stats.caseStats.mixed]);
    const sepArrays = [stats.separatorStats.underscore, stats.separatorStats.hyphen, stats.separatorStats.none];
    const dominantSep = Math.max(...sepArrays.map((a) => a.length));
    stats.separatorStats.consistency = Math.round((dominantSep + (stats.separatorStats.both.length === 0 ? 0 : 0)) / totalTags * 100);
    stats.specialCharStats.consistency = Math.round(stats.specialCharStats.clean.length / totalTags * 100);
    return stats;
  }
  async findInvalidTagFormats() {
    const invalidFiles = [];
    const files = this.getFilteredFiles();
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.frontmatter)) continue;
      const issues = [];
      const fm = cache.frontmatter;
      const checkKey = (key, value) => {
        if (value === void 0 || value === null) return;
        if (typeof value === "string") {
          if (value.includes(",")) {
            issues.push(`"${key}" uses comma-separated format instead of YAML array`);
          } else if (value.trim().length > 0 && value.trim().includes(" ")) {
            issues.push(`"${key}" contains spaces - may be invalid`);
          }
        } else if (Array.isArray(value)) {
          value.forEach((t) => {
            if (typeof t === "string" && t.trim().includes(" ")) {
              issues.push(`Tag "${t}" contains spaces`);
            }
          });
        }
      };
      if ("tags" in fm) checkKey("tags", fm.tags);
      if ("tag" in fm) checkKey("tag", fm.tag);
      if (issues.length > 0) {
        invalidFiles.push({
          path: file.path,
          file,
          issues
        });
      }
    }
    return invalidFiles;
  }
  async findEmptyTags() {
    const emptyFiles = [];
    const files = this.getFilteredFiles();
    for (const file of files) {
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.frontmatter)) continue;
      const fm = cache.frontmatter;
      if ("tags" in fm) {
        const val = fm.tags;
        if (val === null || val === void 0 || Array.isArray(val) && val.length === 0) {
          emptyFiles.push(file);
        }
      }
    }
    return emptyFiles;
  }
  async fixAndStandardizeTags(file) {
    var _a;
    let modified = false;
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      if (fm.tags) {
        if (typeof fm.tags === "string") {
          fm.tags = fm.tags.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
          modified = true;
        }
      }
    });
    if (this.settings.tagFormat === "inline") {
      const content = await this.app.vault.read(file);
      const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
      if (fmMatch) {
        const originalFm = fmMatch[1];
        const listPattern = /^(tags?):\s*(?:\n\s*-.*)+/m;
        if (listPattern.test(originalFm)) {
          const cache = this.app.metadataCache.getFileCache(file);
          const tags = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags;
          if (Array.isArray(tags)) {
            const inlineString = `tags: [${tags.join(", ")}]`;
            const newFm = originalFm.replace(listPattern, inlineString);
            const newContent = content.replace(originalFm, newFm);
            if (newContent !== content) {
              await this.app.vault.modify(file, newContent);
              modified = true;
            }
          }
        }
      }
    }
    return modified;
  }
  async standardizeAllTags() {
    const files = this.getFilteredFiles();
    if (files.length === 0) {
      new import_obsidian.Notice("No files to standardize.");
      return;
    }
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    let count = 0;
    let modifiedCount = 0;
    for (const file of files) {
      try {
        await this.fixAndStandardizeTags(file);
        modifiedCount++;
        count++;
        progressModal.update(count);
      } catch (e) {
        console.error(`Failed to standardize ${file.path}`, e);
      }
    }
    progressModal.close();
    new import_obsidian.Notice(`Standardization check complete on ${count} files.`);
  }
  // --- Aliases ---
  async applyAliases(file) {
    const aliases = this.settings.aliases;
    if (Object.keys(aliases).length === 0) return;
    let modified = false;
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const processSingleTag = (t) => {
        const hasHash = t.startsWith("#");
        const raw = hasHash ? t.substring(1) : t;
        if (aliases[raw]) {
          modified = true;
          return hasHash ? "#" + aliases[raw] : aliases[raw];
        }
        return t;
      };
      if (fm.tags) {
        fm.tags = Array.isArray(fm.tags) ? fm.tags.map(processSingleTag) : processSingleTag(fm.tags);
      }
      if (fm.tag) {
        fm.tag = Array.isArray(fm.tag) ? fm.tag.map(processSingleTag) : processSingleTag(fm.tag);
      }
    });
    if (modified) {
      for (const [alias, canonical] of Object.entries(aliases)) {
        const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        const regex = new RegExp(`(^|\\s)(#)(${escapeRegExp(alias)})(?=[\\s\\/]|$)`, "gu");
        await this.app.vault.process(
          file,
          (data) => data.replace(regex, (m, prefix, hash) => prefix + hash + canonical)
        );
      }
    }
  }
  // --- Core Processing ---
  async processFile(file) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const processSingleTag = (t) => {
        const hasHash = t.startsWith("#");
        const clean = hasHash ? t.substring(1) : t;
        const converted = this.convertTagContent(clean);
        return hasHash ? "#" + converted : converted;
      };
      if (fm.tags) {
        fm.tags = Array.isArray(fm.tags) ? fm.tags.map(processSingleTag) : processSingleTag(fm.tags);
      }
      if (fm.tag) {
        fm.tag = Array.isArray(fm.tag) ? fm.tag.map(processSingleTag) : processSingleTag(fm.tag);
      }
    });
    await this.app.vault.process(file, (data) => this.transformContent(data));
  }
  convertTagContent(tagContent) {
    const parts = tagContent.split("/");
    const processedParts = parts.map((part, index) => {
      if (index > 0 && !this.settings.applyToNestedTags) return part;
      return this.transformSegment(part);
    });
    return processedParts.join("/");
  }
  transformSegment(segment) {
    let s = segment;
    if (this.settings.removeSpecialChars) {
      s = s.replace(/[^\p{L}\p{N}\-_]/gu, "");
    }
    if (this.settings.separatorStrategy === "snake") {
      s = s.replace(/-/g, "_");
    } else if (this.settings.separatorStrategy === "kebab") {
      s = s.replace(/_/g, "-");
    }
    if (this.settings.caseStrategy === "lowercase") {
      s = s.toLowerCase();
    } else if (this.settings.caseStrategy === "uppercase") {
      s = s.toUpperCase();
    }
    return s;
  }
  getAllTags() {
    const tags = this.app.metadataCache.getTags() || {};
    return Object.keys(tags).map((t) => t.substring(1)).sort();
  }
};
var ProgressModal = class extends import_obsidian.Modal {
  constructor(app, total) {
    super(app);
    this.total = total;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-progress-modal");
    new import_obsidian.Setting(contentEl).setName("Processing...").setHeading();
    const container = contentEl.createDiv({ cls: "btm-progress-container" });
    this.progressBar = container.createDiv({ cls: "btm-progress-bar" });
    this.progressBar.createDiv({ cls: "btm-progress-fill" });
    this.progressText = contentEl.createDiv({ cls: "btm-progress-text", text: `0 / ${this.total}` });
  }
  update(current) {
    const percent = Math.round(current / this.total * 100);
    const fill = this.progressBar.querySelector(".btm-progress-fill");
    if (fill) fill.style.width = `${percent}%`;
    this.progressText.textContent = `${current} / ${this.total} (${percent}%)`;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PreviewModal = class extends import_obsidian.Modal {
  constructor(app, plugin, preview, onConfirm) {
    super(app);
    this.plugin = plugin;
    this.preview = preview;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-preview-modal");
    new import_obsidian.Setting(contentEl).setName("Preview Changes").setHeading();
    contentEl.createEl("p", { text: `${this.preview.affectedFiles.length} files will be modified (${this.preview.totalChanges} changes)` });
    const listEl = contentEl.createDiv({ cls: "btm-preview-list" });
    for (const file of this.preview.affectedFiles) {
      const fileEl = listEl.createDiv({ cls: "btm-preview-file" });
      const headerEl = fileEl.createDiv({ cls: "btm-preview-file-header" });
      const checkbox = headerEl.createEl("input", { type: "checkbox" });
      checkbox.checked = file.included;
      checkbox.addEventListener("change", () => {
        file.included = checkbox.checked;
      });
      headerEl.createSpan({ text: file.path, cls: "btm-preview-file-path" });
      headerEl.createSpan({ text: ` (${file.changes.length} changes)`, cls: "btm-preview-file-count" });
      const changesEl = fileEl.createDiv({ cls: "btm-preview-changes" });
      for (const change of file.changes.slice(0, 5)) {
        const changeEl = changesEl.createDiv({ cls: "btm-preview-change" });
        changeEl.createDiv({ cls: "btm-diff-remove", text: `L${change.line}: ${change.before}` });
        changeEl.createDiv({ cls: "btm-diff-add", text: `L${change.line}: ${change.after}` });
      }
      if (file.changes.length > 5) {
        changesEl.createDiv({ text: `... and ${file.changes.length - 5} more`, cls: "btm-more" });
      }
    }
    const btnContainer = contentEl.createDiv({ cls: "btm-button-row" });
    const selectAllBtn = btnContainer.createEl("button", { text: "Select All" });
    selectAllBtn.onclick = () => {
      this.preview.affectedFiles.forEach((f) => f.included = true);
      listEl.querySelectorAll('input[type="checkbox"]').forEach((cb) => cb.checked = true);
    };
    const selectNoneBtn = btnContainer.createEl("button", { text: "Select None" });
    selectNoneBtn.onclick = () => {
      this.preview.affectedFiles.forEach((f) => f.included = false);
      listEl.querySelectorAll('input[type="checkbox"]').forEach((cb) => cb.checked = false);
    };
    const cancelBtn = btnContainer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = btnContainer.createEl("button", { text: "Apply Changes", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.close();
      this.onConfirm(this.preview.affectedFiles.filter((f) => f.included));
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var HistoryModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-history-modal");
    new import_obsidian.Setting(contentEl).setName("Operation History").setHeading();
    if (this.plugin.settings.operationHistory.length === 0) {
      contentEl.createEl("p", { text: "No operations recorded yet." });
      return;
    }
    const listEl = contentEl.createDiv({ cls: "btm-history-list" });
    for (const op of this.plugin.settings.operationHistory) {
      const itemEl = listEl.createDiv({ cls: "btm-history-item" });
      const date = new Date(op.timestamp);
      const timeStr = date.toLocaleDateString() + " " + date.toLocaleTimeString();
      itemEl.createDiv({ cls: "btm-history-time", text: timeStr });
      itemEl.createDiv({ cls: "btm-history-desc", text: op.description });
      itemEl.createDiv({ cls: "btm-history-files", text: `${op.changes.length} files affected` });
      if (op === this.plugin.settings.operationHistory[0]) {
        const revertBtn = itemEl.createEl("button", { text: "Undo", cls: "btm-revert-btn" });
        revertBtn.onclick = async () => {
          this.close();
          await this.plugin.undoLastOperation();
        };
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagHierarchyModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-hierarchy-modal");
    new import_obsidian.Setting(contentEl).setName("Tag Hierarchy").setHeading();
    const hierarchy = this.plugin.getTagHierarchy();
    if (hierarchy.length === 0) {
      contentEl.createEl("p", { text: "No tags found." });
      return;
    }
    const treeEl = contentEl.createDiv({ cls: "btm-tree" });
    this.renderTree(treeEl, hierarchy, 0);
  }
  renderTree(container, nodes, depth) {
    for (const node of nodes.sort((a, b) => a.name.localeCompare(b.name))) {
      const nodeEl = container.createDiv({ cls: "btm-tree-node" });
      nodeEl.style.paddingLeft = `${depth * 20}px`;
      const hasChildren = node.children.length > 0;
      const headerEl = nodeEl.createDiv({ cls: "btm-tree-header" });
      const iconEl = headerEl.createSpan({ cls: "btm-tree-icon" });
      (0, import_obsidian.setIcon)(iconEl, hasChildren ? "folder" : "tag");
      headerEl.createSpan({ text: node.name, cls: "btm-tree-name" });
      if (node.count > 0) {
        headerEl.createSpan({ text: ` (${node.count})`, cls: "btm-tree-count" });
      }
      if (hasChildren) {
        const childContainer = container.createDiv({ cls: "btm-tree-children" });
        this.renderTree(childContainer, node.children, depth + 1);
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var InvalidTagsModal = class extends import_obsidian.Modal {
  constructor(app, plugin, invalidFiles) {
    super(app);
    this.plugin = plugin;
    this.invalidFiles = invalidFiles;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-invalid-modal");
    new import_obsidian.Setting(contentEl).setName("Files with Invalid Tag Format").setDesc(`${this.invalidFiles.length} file${this.invalidFiles.length > 1 ? "s" : ""} found with tag format issues`).setHeading();
    const listEl = contentEl.createDiv({ cls: "btm-invalid-list" });
    for (const item of this.invalidFiles) {
      const itemEl = listEl.createDiv({ cls: "btm-invalid-item" });
      const headerEl = itemEl.createDiv({ cls: "btm-invalid-item-header" });
      const iconEl = headerEl.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(iconEl, "file-warning");
      const linkEl = headerEl.createEl("a", {
        text: item.path,
        cls: "btm-invalid-file-link"
      });
      linkEl.onclick = (e) => {
        e.preventDefault();
        this.close();
        this.app.workspace.openLinkText(item.path, "", false);
      };
      const fixBtn = headerEl.createEl("button", { text: "Fix", cls: "btm-view-invalid-btn" });
      fixBtn.onclick = async () => {
        await this.plugin.fixAndStandardizeTags(item.file);
        new import_obsidian.Notice(`Fixed tags in ${item.file.basename}`);
        itemEl.remove();
      };
      const issuesEl = itemEl.createDiv({ cls: "btm-invalid-issues" });
      for (const issue of item.issues) {
        const issueEl = issuesEl.createDiv({ cls: "btm-invalid-issue" });
        const issueIcon = issueEl.createSpan({ cls: "btm-icon" });
        (0, import_obsidian.setIcon)(issueIcon, "alert-circle");
        issueEl.createSpan({ text: " " + issue });
      }
    }
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const fixAllBtn = btnRow.createEl("button", { text: "Fix All", cls: "mod-cta" });
    fixAllBtn.onclick = async () => {
      const progressModal = new ProgressModal(this.app, this.invalidFiles.length);
      progressModal.open();
      let count = 0;
      for (const item of this.invalidFiles) {
        try {
          await this.plugin.fixAndStandardizeTags(item.file);
          count++;
          progressModal.update(count);
        } catch (e) {
          console.error("Failed to fix " + item.path, e);
        }
      }
      progressModal.close();
      new import_obsidian.Notice(`Fixed tags in ${count} files.`);
      this.close();
    };
    const closeBtn = btnRow.createEl("button", { text: "Close" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var EmptyTagsModal = class extends import_obsidian.Modal {
  constructor(app, emptyFiles) {
    super(app);
    this.emptyFiles = emptyFiles;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-invalid-modal");
    new import_obsidian.Setting(contentEl).setName("Files with Empty Tags").setDesc(`${this.emptyFiles.length} file${this.emptyFiles.length > 1 ? "s" : ""} found`).setHeading();
    const listEl = contentEl.createDiv({ cls: "btm-invalid-list" });
    for (const file of this.emptyFiles) {
      const itemEl = listEl.createDiv({ cls: "btm-invalid-item" });
      const headerEl = itemEl.createDiv({ cls: "btm-invalid-item-header" });
      const iconEl = headerEl.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(iconEl, "file");
      const linkEl = headerEl.createEl("a", {
        text: file.path,
        cls: "btm-invalid-file-link"
      });
      linkEl.onclick = (e) => {
        e.preventDefault();
        this.close();
        this.app.workspace.openLinkText(file.path, "", false);
      };
    }
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const closeBtn = btnRow.createEl("button", { text: "Close" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var InlineTagsModal = class extends import_obsidian.Modal {
  constructor(app, inlineFiles) {
    super(app);
    this.inlineFiles = inlineFiles;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-invalid-modal");
    new import_obsidian.Setting(contentEl).setName("Notes with Inline Tags").setDesc(`${this.inlineFiles.length} notes found with tags in body`).setHeading();
    const listEl = contentEl.createDiv({ cls: "btm-invalid-list" });
    for (const item of this.inlineFiles) {
      const itemEl = listEl.createDiv({ cls: "btm-invalid-item" });
      const headerEl = itemEl.createDiv({ cls: "btm-invalid-item-header" });
      const iconEl = headerEl.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(iconEl, "file-text");
      const titleEl = headerEl.createEl("a", {
        text: item.file.basename,
        cls: "btm-invalid-file-link"
      });
      titleEl.onclick = () => {
        this.close();
        this.app.workspace.openLinkText(item.file.path, "", false);
      };
      const countSpan = headerEl.createSpan({ text: ` \u2014 ${item.count} inline tags`, cls: "btm-highlight" });
      countSpan.style.marginLeft = "10px";
      countSpan.style.fontSize = "12px";
      const tagsEl = itemEl.createDiv({ cls: "btm-metric-details" });
      tagsEl.style.marginTop = "8px";
      for (const tag of item.tags) {
        tagsEl.createSpan({ text: "#" + tag });
      }
    }
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const closeBtn = btnRow.createEl("button", { text: "Close" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var NestedFilesModal = class extends import_obsidian.Modal {
  constructor(app, nestedFiles) {
    super(app);
    this.nestedFiles = nestedFiles;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-invalid-modal");
    new import_obsidian.Setting(contentEl).setName("Notes with Nested Tags").setDesc(`${this.nestedFiles.length} notes found containing hierarchical tags`).setHeading();
    const listEl = contentEl.createDiv({ cls: "btm-invalid-list" });
    for (const item of this.nestedFiles) {
      const itemEl = listEl.createDiv({ cls: "btm-invalid-item" });
      const headerEl = itemEl.createDiv({ cls: "btm-invalid-item-header" });
      const iconEl = headerEl.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(iconEl, "file-text");
      const titleEl = headerEl.createEl("a", {
        text: item.file.basename,
        cls: "btm-invalid-file-link"
      });
      titleEl.onclick = () => {
        this.close();
        this.app.workspace.openLinkText(item.file.path, "", false);
      };
      const countSpan = headerEl.createSpan({ text: ` \u2014 ${item.count} nested tags`, cls: "btm-highlight" });
      countSpan.style.marginLeft = "10px";
      countSpan.style.fontSize = "12px";
      const tagsEl = itemEl.createDiv({ cls: "btm-metric-details" });
      tagsEl.style.marginTop = "8px";
      for (const tag of item.tags) {
        tagsEl.createSpan({ text: "#" + tag });
      }
    }
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const closeBtn = btnRow.createEl("button", { text: "Close" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagListModal = class extends import_obsidian.Modal {
  constructor(app, title, tags) {
    super(app);
    this.title = title;
    this.tags = tags;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-tag-list-modal");
    new import_obsidian.Setting(contentEl).setName(this.title).setDesc(`${this.tags.length} tags found`).setHeading();
    const listEl = contentEl.createDiv({ cls: "btm-invalid-list" });
    for (const tag of this.tags) {
      const itemEl = listEl.createDiv({ cls: "btm-invalid-item btm-tag-item" });
      const tagText = tag.startsWith("#") ? tag : "#" + tag;
      const tagEl = itemEl.createSpan({ text: tagText, cls: "btm-tag-pill" });
      const btn = itemEl.createEl("button", { text: "Search", cls: "btm-search-btn" });
      btn.onclick = () => {
        var _a;
        this.close();
        const searchPlugin = (_a = this.app.internalPlugins) == null ? void 0 : _a.getPluginById("global-search");
        if (searchPlugin == null ? void 0 : searchPlugin.instance) {
          searchPlugin.instance.openGlobalSearch(`tag:${tagText}`);
        } else {
          new import_obsidian.Notice("Global Search plugin not enabled");
        }
      };
    }
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const closeBtn = btnRow.createEl("button", { text: "Close" });
    closeBtn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var OrphanTagsModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-orphan-modal");
    new import_obsidian.Setting(contentEl).setName("Orphaned Tags").setDesc(`Tags used in fewer than ${this.plugin.settings.orphanThreshold} files`).setHeading();
    const orphans = this.plugin.findOrphanedTags();
    if (orphans.length === 0) {
      contentEl.createEl("p", { text: "No orphaned tags found!" });
      return;
    }
    contentEl.createEl("p", { text: `Found ${orphans.length} orphaned tags:` });
    const listEl = contentEl.createDiv({ cls: "btm-orphan-list" });
    for (const { tag, count } of orphans) {
      const itemEl = listEl.createDiv({ cls: "btm-orphan-item" });
      itemEl.createSpan({ text: tag, cls: "btm-orphan-tag" });
      itemEl.createSpan({ text: ` (${count} use${count === 1 ? "" : "s"})`, cls: "btm-orphan-count" });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagSuggest = class extends import_obsidian.SuggestModal {
  constructor(app, plugin, onSelect) {
    super(app);
    this.plugin = plugin;
    this.onSelect = onSelect;
    this.tagCounts = this.plugin.app.metadataCache.getTags() || {};
  }
  getSuggestions(query) {
    const tags = this.plugin.getAllTags();
    if (!query) return tags.slice(0, 50);
    return tags.filter((t) => t.toLowerCase().includes(query.toLowerCase())).slice(0, 50);
  }
  renderSuggestion(tag, el) {
    const count = this.tagCounts["#" + tag] || 0;
    el.createSpan({ text: `#${tag}`, cls: "btm-suggest-tag" });
    el.createSpan({ text: ` (${count})`, cls: "btm-suggest-count" });
  }
  onChooseSuggestion(tag) {
    this.onSelect(tag);
  }
};
var MultiTagSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onConfirm) {
    super(app);
    this.selectedTags = /* @__PURE__ */ new Set();
    this.plugin = plugin;
    this.onConfirm = onConfirm;
    this.tagCounts = this.plugin.app.metadataCache.getTags() || {};
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-multiselect-modal");
    new import_obsidian.Setting(contentEl).setName("Select Tags to Merge").setHeading();
    const searchDiv = contentEl.createDiv({ cls: "btm-search-container" });
    this.searchInput = new import_obsidian.TextComponent(searchDiv).setPlaceholder("Search tags...");
    this.searchInput.inputEl.addEventListener("input", () => this.renderList());
    const selectedDiv = contentEl.createDiv({ cls: "btm-selected-tags" });
    selectedDiv.id = "btm-selected-display";
    this.listEl = contentEl.createDiv({ cls: "btm-tag-list" });
    this.renderList();
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = btnRow.createEl("button", { text: "Confirm Selection", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.close();
      this.onConfirm(Array.from(this.selectedTags));
    };
  }
  renderList() {
    this.listEl.empty();
    const query = this.searchInput.getValue().toLowerCase();
    const tags = this.plugin.getAllTags();
    const filtered = query ? tags.filter((t) => t.toLowerCase().includes(query)) : tags;
    for (const tag of filtered.slice(0, 100)) {
      const count = this.tagCounts["#" + tag] || 0;
      const itemEl = this.listEl.createDiv({ cls: "btm-tag-item" });
      const checkbox = itemEl.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedTags.has(tag);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedTags.add(tag);
        } else {
          this.selectedTags.delete(tag);
        }
        this.updateSelectedDisplay();
      });
      itemEl.createSpan({ text: `#${tag}`, cls: "btm-tag-name" });
      itemEl.createSpan({ text: ` (${count})`, cls: "btm-tag-count" });
    }
    this.updateSelectedDisplay();
  }
  updateSelectedDisplay() {
    const display = this.contentEl.querySelector("#btm-selected-display");
    if (display) {
      display.empty();
      if (this.selectedTags.size > 0) {
        display.createSpan({ text: `Selected (${this.selectedTags.size}): ` });
        display.createSpan({ text: Array.from(this.selectedTags).map((t) => "#" + t).join(", "), cls: "btm-selected-list" });
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FolderSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, currentFolders, onConfirm) {
    super(app);
    this.plugin = plugin;
    this.selectedFolders = new Set(currentFolders.filter((f) => f));
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-folder-modal");
    new import_obsidian.Setting(contentEl).setName("Select Folders").setHeading();
    const searchDiv = contentEl.createDiv({ cls: "btm-search-container" });
    this.searchInput = new import_obsidian.TextComponent(searchDiv).setPlaceholder("Search folders...");
    this.searchInput.inputEl.addEventListener("input", () => this.renderList());
    const selectedDiv = contentEl.createDiv({ cls: "btm-selected-tags" });
    selectedDiv.id = "btm-selected-folders-display";
    this.listEl = contentEl.createDiv({ cls: "btm-tag-list" });
    this.renderList();
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = btnRow.createEl("button", { text: "Confirm Selection", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.close();
      this.onConfirm(Array.from(this.selectedFolders));
    };
  }
  getAllFolders() {
    const folders = [];
    const collectFolders = (folder) => {
      if (folder.path && folder.path !== "/") {
        folders.push(folder.path);
      }
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder) {
          collectFolders(child);
        }
      }
    };
    collectFolders(this.app.vault.getRoot());
    return folders.sort();
  }
  renderList() {
    this.listEl.empty();
    const query = this.searchInput.getValue().toLowerCase();
    const folders = this.getAllFolders();
    const filtered = query ? folders.filter((f) => f.toLowerCase().includes(query)) : folders;
    if (filtered.length === 0) {
      this.listEl.createEl("p", { text: "No folders found", cls: "btm-no-results" });
      return;
    }
    for (const folder of filtered.slice(0, 100)) {
      const itemEl = this.listEl.createDiv({ cls: "btm-tag-item" });
      const checkbox = itemEl.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedFolders.has(folder);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedFolders.add(folder);
        } else {
          this.selectedFolders.delete(folder);
        }
        this.updateSelectedDisplay();
      });
      const folderIcon = itemEl.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(folderIcon, "folder");
      itemEl.createSpan({ text: " " + folder, cls: "btm-folder-name" });
    }
    this.updateSelectedDisplay();
  }
  updateSelectedDisplay() {
    const display = this.contentEl.querySelector("#btm-selected-folders-display");
    if (display) {
      display.empty();
      if (this.selectedFolders.size > 0) {
        display.createSpan({ text: `Selected (${this.selectedFolders.size}): ` });
        display.createSpan({ text: Array.from(this.selectedFolders).join(", "), cls: "btm-selected-list" });
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagManagerModal = class extends import_obsidian.Modal {
  // For layout consistency
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-dashboard");
    new import_obsidian.Setting(contentEl).setName("Bulk Tag Manager").setHeading();
    const overviewBox = contentEl.createDiv({ cls: "btm-section-box" });
    const overviewHeader = overviewBox.createDiv({ cls: "btm-collapsible-header" });
    overviewHeader.createSpan({ text: "Overview (Stats)" });
    const arrow = overviewHeader.createSpan({ cls: "btm-header-arrow" });
    (0, import_obsidian.setIcon)(arrow, "chevron-down");
    this.statsEl = overviewBox.createDiv({ cls: "btm-collapsible-content" });
    this.updateStats();
    let isExpanded = true;
    overviewHeader.onclick = () => {
      isExpanded = !isExpanded;
      if (isExpanded) {
        this.statsEl.removeClass("is-collapsed");
        arrow.removeClass("is-collapsed");
      } else {
        this.statsEl.addClass("is-collapsed");
        arrow.addClass("is-collapsed");
      }
    };
    const renameBox = contentEl.createDiv({ cls: "btm-section-box" });
    renameBox.createDiv({ cls: "btm-collapsible-header" }).createSpan({ text: "Rename Tag" });
    const renameContainer = renameBox.createDiv({ cls: "btm-aligned-row" });
    const findCol = renameContainer.createDiv({ cls: "btm-field-column" });
    findCol.createEl("label", { text: "Find" });
    this.findInput = new import_obsidian.TextComponent(findCol).setPlaceholder("#old-tag");
    const findSuggestBtn = findCol.createEl("button", { cls: "btm-suggest-btn btm-icon-btn btm-small-center-btn" });
    (0, import_obsidian.setIcon)(findSuggestBtn, "search");
    findSuggestBtn.createSpan({ text: " Search" });
    const tagCountDisplay = findCol.createDiv({ cls: "btm-tag-count-display", attr: { style: "font-size: 11px; margin-top: 4px; color: var(--text-muted);" } });
    findSuggestBtn.onclick = () => new TagSuggest(this.app, this.plugin, (t) => {
      this.findInput.setValue(t);
      const tags = this.plugin.app.metadataCache.getTags() || {};
      const count = tags["#" + t] || 0;
      tagCountDisplay.textContent = `${count} pos`;
    }).open();
    const replaceCol = renameContainer.createDiv({ cls: "btm-field-column" });
    replaceCol.createEl("label", { text: "Replace" });
    this.replaceInput = new import_obsidian.TextComponent(replaceCol).setPlaceholder("#new-tag");
    const btnRename = renameContainer.createEl("button", { text: "Rename", cls: "mod-cta btm-action-btn" });
    btnRename.onclick = async () => {
      const oldT = this.findInput.getValue();
      const newT = this.replaceInput.getValue();
      if (oldT && newT) {
        this.close();
        await this.plugin.renameTag(oldT, newT);
      } else {
        new import_obsidian.Notice("Please fill both fields.");
      }
    };
    const mergeBox = contentEl.createDiv({ cls: "btm-section-box" });
    mergeBox.createDiv({ cls: "btm-collapsible-header" }).createSpan({ text: "Merge Tags" });
    const mergeContainer = mergeBox.createDiv({ cls: "btm-aligned-row" });
    const sourceCol = mergeContainer.createDiv({ cls: "btm-field-column" });
    sourceCol.createEl("label", { text: "Source tags" });
    this.mergeSourcesInput = new import_obsidian.TextComponent(sourceCol).setPlaceholder("#tag1, #tag2");
    const selectTagsBtn = sourceCol.createEl("button", { cls: "btm-suggest-btn btm-icon-btn btm-small-center-btn" });
    (0, import_obsidian.setIcon)(selectTagsBtn, "list-filter");
    selectTagsBtn.createSpan({ text: " Select" });
    selectTagsBtn.onclick = () => new MultiTagSelectModal(this.app, this.plugin, (tags) => {
      this.mergeSourcesInput.setValue(tags.map((t) => "#" + t).join(", "));
    }).open();
    const targetCol = mergeContainer.createDiv({ cls: "btm-field-column" });
    targetCol.createEl("label", { text: "Target" });
    this.mergeTargetInput = new import_obsidian.TextComponent(targetCol).setPlaceholder("#merged");
    const targetSuggestBtn = targetCol.createEl("button", { cls: "btm-suggest-btn btm-icon-btn btm-small-center-btn" });
    (0, import_obsidian.setIcon)(targetSuggestBtn, "search");
    targetSuggestBtn.createSpan({ text: " Search" });
    targetSuggestBtn.onclick = () => new TagSuggest(this.app, this.plugin, (t) => this.mergeTargetInput.setValue(t)).open();
    const btnMerge = mergeContainer.createEl("button", { text: "Merge", cls: "mod-cta btm-action-btn" });
    btnMerge.onclick = async () => {
      const sources = this.mergeSourcesInput.getValue().split(",").map((s) => s.trim()).filter((s) => s);
      const target = this.mergeTargetInput.getValue().trim();
      if (sources.length > 0 && target) {
        this.close();
        await this.plugin.mergeTags(sources, target);
      } else {
        new import_obsidian.Notice("Please provide source tags and a target.");
      }
    };
    const patternBox = contentEl.createDiv({ cls: "btm-section-box" });
    patternBox.createDiv({ cls: "btm-collapsible-header" }).createSpan({ text: "Pattern Rename (Regex)" });
    const patternContainer = patternBox.createDiv({ cls: "btm-aligned-row" });
    const patternCol = patternContainer.createDiv({ cls: "btm-field-column" });
    patternCol.createEl("label", { text: "Pattern" });
    this.patternInput = new import_obsidian.TextComponent(patternCol).setPlaceholder("^old-(.*)");
    const patternRepCol = patternContainer.createDiv({ cls: "btm-field-column" });
    patternRepCol.createEl("label", { text: "Replacement" });
    this.patternReplaceInput = new import_obsidian.TextComponent(patternRepCol).setPlaceholder("new-$1");
    const btnPattern = patternContainer.createEl("button", { text: "Apply", cls: "mod-cta btm-action-btn" });
    btnPattern.onclick = async () => {
      const pattern = this.patternInput.getValue();
      const replacement = this.patternReplaceInput.getValue();
      if (pattern) {
        this.close();
        await this.plugin.batchRename(pattern, replacement);
      } else {
        new import_obsidian.Notice("Please provide a pattern.");
      }
    };
    const settingsBox = contentEl.createDiv({ cls: "btm-section-box" });
    settingsBox.createDiv({ cls: "btm-collapsible-header" }).createSpan({ text: "Bulk Settings" });
    new import_obsidian.Setting(settingsBox).setName("Case Strategy").addDropdown((dropdown) => dropdown.addOption("lowercase", "Lowercase").addOption("uppercase", "Uppercase").addOption("none", "No Change").setValue(this.plugin.settings.caseStrategy).onChange(async (value) => {
      this.plugin.settings.caseStrategy = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    new import_obsidian.Setting(settingsBox).setName("Separator Style").addDropdown((dropdown) => dropdown.addOption("preserve", "Preserve").addOption("snake", "Snake Case").addOption("kebab", "Kebab Case").setValue(this.plugin.settings.separatorStrategy).onChange(async (value) => {
      this.plugin.settings.separatorStrategy = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    new import_obsidian.Setting(settingsBox).setName("Remove Special Characters").addToggle((toggle) => toggle.setValue(this.plugin.settings.removeSpecialChars).onChange(async (value) => {
      this.plugin.settings.removeSpecialChars = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    new import_obsidian.Setting(settingsBox).setName("Apply to Nested Tags").addToggle((toggle) => toggle.setValue(this.plugin.settings.applyToNestedTags).onChange(async (value) => {
      this.plugin.settings.applyToNestedTags = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    const scopeBox = contentEl.createDiv({ cls: "btm-section-box" });
    scopeBox.createDiv({ cls: "btm-collapsible-header" }).createSpan({ text: "Scope Filter" });
    new import_obsidian.Setting(scopeBox).setName("Enable Scope Filter").setDesc("Limit operations to specific folders").addToggle((toggle) => toggle.setValue(this.plugin.settings.scopeFilter.enabled).onChange(async (value) => {
      this.plugin.settings.scopeFilter.enabled = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    const includeRow = scopeBox.createDiv({ cls: "btm-scope-row", attr: { style: "margin-bottom: 8px;" } });
    includeRow.createSpan({ text: "Include: " });
    const includeDisplay = includeRow.createSpan({ text: this.plugin.settings.scopeFilter.includeFolders.join(", ") || "(all)", cls: "btm-folder-display", attr: { style: "margin-right: 8px;" } });
    const includeBtn = includeRow.createEl("button", { cls: "btm-suggest-btn btm-icon-btn btm-small-center-btn" });
    (0, import_obsidian.setIcon)(includeBtn, "folder-plus");
    includeBtn.createSpan({ text: " Select" });
    includeBtn.onclick = () => new FolderSelectModal(this.app, this.plugin, this.plugin.settings.scopeFilter.includeFolders, async (f) => {
      this.plugin.settings.scopeFilter.includeFolders = f;
      await this.plugin.saveSettings();
      includeDisplay.textContent = f.join(", ") || "(all)";
      this.updateStats();
    }).open();
    const excludeRow = scopeBox.createDiv({ cls: "btm-scope-row" });
    excludeRow.createSpan({ text: "Exclude: " });
    const excludeDisplay = excludeRow.createSpan({ text: this.plugin.settings.scopeFilter.excludeFolders.join(", ") || "(none)", cls: "btm-folder-display", attr: { style: "margin-right: 8px;" } });
    const excludeBtn = excludeRow.createEl("button", { cls: "btm-suggest-btn btm-icon-btn btm-small-center-btn" });
    (0, import_obsidian.setIcon)(excludeBtn, "folder-minus");
    excludeBtn.createSpan({ text: " Select" });
    excludeBtn.onclick = () => new FolderSelectModal(this.app, this.plugin, this.plugin.settings.scopeFilter.excludeFolders, async (f) => {
      this.plugin.settings.scopeFilter.excludeFolders = f;
      await this.plugin.saveSettings();
      excludeDisplay.textContent = f.join(", ") || "(none)";
      this.updateStats();
    }).open();
    const actionBox = contentEl.createDiv({ cls: "btm-section-box" });
    actionBox.createDiv({ cls: "btm-collapsible-header" }).createSpan({ text: "Actions" });
    const actionRow = actionBox.createDiv({ cls: "btm-action-row" });
    const btnConvert = this.createIconButton(actionRow, "refresh-cw", "Convert All", "mod-cta");
    (0, import_obsidian.setTooltip)(btnConvert, "Run full conversion/standardization based on settings");
    btnConvert.onclick = async () => {
      this.close();
      await this.plugin.runConversionWithPreview();
    };
    const btnList = this.createIconButton(actionRow, "list", "Tag List");
    (0, import_obsidian.setTooltip)(btnList, "View all tags in a list");
    btnList.onclick = async () => {
      this.close();
      await this.plugin.generateTagList();
    };
    const btnHierarchy = this.createIconButton(actionRow, "git-branch", "Hierarchy");
    (0, import_obsidian.setTooltip)(btnHierarchy, "View tag hierarchy tree");
    btnHierarchy.onclick = () => {
      this.close();
      new TagHierarchyModal(this.app, this.plugin).open();
    };
    const btnOrphans = this.createIconButton(actionRow, "alert-circle", "Orphans");
    (0, import_obsidian.setTooltip)(btnOrphans, "Find orphaned tags");
    btnOrphans.onclick = () => {
      this.close();
      new OrphanTagsModal(this.app, this.plugin).open();
    };
    const btnHistory = this.createIconButton(actionRow, "history", "History");
    (0, import_obsidian.setTooltip)(btnHistory, "View and revert recent changes");
    btnHistory.onclick = () => {
      this.close();
      new HistoryModal(this.app, this.plugin).open();
    };
    const btnStandardize = this.createIconButton(actionRow, "check-square", "Fix Invalid");
    (0, import_obsidian.setTooltip)(btnStandardize, "Standardize formats (commas/spaces)");
    btnStandardize.onclick = async () => {
      this.close();
      await this.plugin.standardizeAllTags();
    };
  }
  createIconButton(container, iconName, text, cls = "") {
    const btn = container.createEl("button", { cls: `btm-icon-btn ${cls}`.trim() });
    const iconEl = btn.createSpan({ cls: "btm-btn-icon" });
    (0, import_obsidian.setIcon)(iconEl, iconName);
    btn.createSpan({ text: " " + text });
    return btn;
  }
  createProgressBar(container, value) {
    const bar = container.createDiv({ cls: "btm-progress-bar-mini" });
    const fill = bar.createDiv({ cls: "btm-progress-fill-mini" });
    fill.style.width = `${value}%`;
    if (value < 50) fill.addClass("btm-progress-low");
    else if (value < 80) fill.addClass("btm-progress-medium");
    else fill.addClass("btm-progress-high");
  }
  updateStats() {
    this.statsEl.empty();
    this.statsEl.addClass("btm-standardization-panel");
    const files = this.plugin.getFilteredFiles();
    const stats = this.plugin.analyzeTagStandardization(files);
    const headerRow = this.statsEl.createDiv({ cls: "btm-stats-header" });
    const tagsItem = headerRow.createSpan({ cls: "btm-stat-item" });
    (0, import_obsidian.setIcon)(tagsItem.createSpan({ cls: "btm-stat-icon" }), "tags");
    tagsItem.createSpan({ text: ` ${stats.totalTags} tags` });
    const filesItem = headerRow.createSpan({ cls: "btm-stat-item" });
    (0, import_obsidian.setIcon)(filesItem.createSpan({ cls: "btm-stat-icon" }), "files");
    filesItem.createSpan({ text: ` ${files.length} files` });
    this.metricsGrid = this.statsEl.createDiv({ cls: "btm-metrics-grid" });
    const createStatLink = (container, count, label, tags) => {
      if (count > 0) {
        const link = container.createEl("a", { text: `${count} ${label}`, cls: "btm-stat-link" });
        link.onclick = () => {
          this.close();
          new TagListModal(this.app, `${label} Tags`, tags).open();
        };
        container.appendText(" ");
      }
    };
    const caseBox = this.metricsGrid.createDiv({ cls: "btm-metric-box" });
    caseBox.createDiv({ text: "Case", cls: "btm-metric-label" });
    this.createProgressBar(caseBox, stats.caseStats.consistency);
    const caseDetails = caseBox.createDiv({ cls: "btm-metric-details" });
    createStatLink(caseDetails, stats.caseStats.lowercase.length, "lower", stats.caseStats.lowercase);
    createStatLink(caseDetails, stats.caseStats.uppercase.length, "UPPER", stats.caseStats.uppercase);
    createStatLink(caseDetails, stats.caseStats.mixed.length, "Mixed", stats.caseStats.mixed);
    const sepBox = this.metricsGrid.createDiv({ cls: "btm-metric-box" });
    sepBox.createDiv({ text: "Separators", cls: "btm-metric-label" });
    this.createProgressBar(sepBox, stats.separatorStats.consistency);
    const sepDetails = sepBox.createDiv({ cls: "btm-metric-details" });
    createStatLink(sepDetails, stats.separatorStats.hyphen.length, "kebab-case", stats.separatorStats.hyphen);
    createStatLink(sepDetails, stats.separatorStats.underscore.length, "snake_case", stats.separatorStats.underscore);
    createStatLink(sepDetails, stats.separatorStats.both.length, "mixed", stats.separatorStats.both);
    createStatLink(sepDetails, stats.separatorStats.none.length, "none", stats.separatorStats.none);
    const specialBox = this.metricsGrid.createDiv({ cls: "btm-metric-box" });
    specialBox.createDiv({ text: "Clean Tags", cls: "btm-metric-label" });
    this.createProgressBar(specialBox, stats.specialCharStats.consistency);
    const specialDetails = specialBox.createDiv({ cls: "btm-metric-details" });
    createStatLink(specialDetails, stats.specialCharStats.clean.length, "clean", stats.specialCharStats.clean);
    createStatLink(specialDetails, stats.specialCharStats.withSpecial.length, "with special chars", stats.specialCharStats.withSpecial);
    const nestBox = this.metricsGrid.createDiv({ cls: "btm-metric-box" });
    nestBox.createDiv({ text: "Hierarchy", cls: "btm-metric-label" });
    const nestDetails = nestBox.createDiv({ cls: "btm-metric-details" });
    createStatLink(nestDetails, stats.nestingStats.flat.length, "flat", stats.nestingStats.flat);
    if (stats.inlineFiles.length > 0) {
      const nestedLink = nestDetails.createEl("a", { text: `${stats.inlineFiles.length} notes with inline tags`, cls: "btm-stat-link" });
      nestedLink.onclick = () => {
        this.close();
        new InlineTagsModal(this.app, stats.inlineFiles).open();
      };
    } else {
      nestDetails.createSpan({ text: "0 notes with inline tags" });
    }
    if (stats.nestedFiles.length > 0) {
      const realNestedLink = nestDetails.createEl("a", { text: `${stats.nestedFiles.length} with nested tags`, cls: "btm-stat-link" });
      realNestedLink.onclick = () => {
        this.close();
        new NestedFilesModal(this.app, stats.nestedFiles).open();
      };
    } else {
      nestDetails.createSpan({ text: "0 with nested tags" });
    }
    const locBox = this.metricsGrid.createDiv({ cls: "btm-metric-box" });
    locBox.createDiv({ text: "Locations", cls: "btm-metric-label" });
    const locDetails = locBox.createDiv({ cls: "btm-metric-details" });
    createStatLink(locDetails, stats.locationStats.frontmatter.length, "frontmatter", stats.locationStats.frontmatter);
    createStatLink(locDetails, stats.locationStats.body.length, "body", stats.locationStats.body);
    const lengthBox = this.metricsGrid.createDiv({ cls: "btm-metric-box" });
    lengthBox.createDiv({ text: "Length", cls: "btm-metric-label" });
    const lengthDetails = lengthBox.createDiv({ cls: "btm-metric-details" });
    lengthDetails.createSpan({ text: `avg: ${stats.lengthStats.avgLength} chars ` });
    createStatLink(lengthDetails, stats.lengthStats.long.length, "long (>25)", stats.lengthStats.long);
    this.checkInvalidTags();
    this.checkEmptyTags();
  }
  async checkEmptyTags() {
    const emptyFiles = await this.plugin.findEmptyTags();
    if (emptyFiles.length > 0) {
      if (this.metricsGrid) {
        const emptyBox = this.metricsGrid.createDiv({ cls: "btm-metric-box btm-info-box" });
        emptyBox.createDiv({ text: "Empty Tags", cls: "btm-metric-label" });
        const detail = emptyBox.createDiv({ cls: "btm-metric-details" });
        const link = detail.createEl("a", { text: `${emptyFiles.length} files` });
        link.onclick = () => {
          this.close();
          new EmptyTagsModal(this.app, emptyFiles).open();
        };
      }
    }
  }
  async checkInvalidTags() {
    const invalidFiles = await this.plugin.findInvalidTagFormats();
    if (invalidFiles.length > 0) {
      let invalidSection = this.statsEl.querySelector(".btm-invalid-section");
      if (!invalidSection) {
        invalidSection = this.statsEl.createDiv({ cls: "btm-invalid-section" });
      }
      invalidSection.empty();
      const warningRow = invalidSection.createDiv({ cls: "btm-invalid-warning" });
      const iconEl = warningRow.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(iconEl, "alert-triangle");
      warningRow.createSpan({ text: ` ${invalidFiles.length} file${invalidFiles.length > 1 ? "s" : ""} with invalid tag format` });
      const viewBtn = warningRow.createEl("button", { text: "View", cls: "btm-view-invalid-btn" });
      viewBtn.onclick = () => {
        this.close();
        new InvalidTagsModal(this.app, this.plugin, invalidFiles).open();
      };
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagLowercaseSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Bulk Tag Manager Settings").setHeading();
    containerEl.createEl("p", { text: "Access the full dashboard via the ribbon icon or command palette." });
    new import_obsidian.Setting(containerEl).setName("Case Strategy").addDropdown((dropdown) => dropdown.addOption("lowercase", "Lowercase").addOption("uppercase", "Uppercase").addOption("none", "No Change").setValue(this.plugin.settings.caseStrategy).onChange(async (value) => {
      this.plugin.settings.caseStrategy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Separator Style").addDropdown((dropdown) => dropdown.addOption("preserve", "Preserve").addOption("snake", "Snake Case").addOption("kebab", "Kebab Case").setValue(this.plugin.settings.separatorStrategy).onChange(async (value) => {
      this.plugin.settings.separatorStrategy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Remove Special Characters").addToggle((toggle) => toggle.setValue(this.plugin.settings.removeSpecialChars).onChange(async (value) => {
      this.plugin.settings.removeSpecialChars = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Apply to Nested Tags").addToggle((toggle) => toggle.setValue(this.plugin.settings.applyToNestedTags).onChange(async (value) => {
      this.plugin.settings.applyToNestedTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Tag Output Format").setDesc("Format for writing tags to frontmatter").addDropdown((dropdown) => dropdown.addOption("inline", "Inline Array [tag1, tag2]").addOption("list", "YAML List (- tag1)").setValue(this.plugin.settings.tagFormat).onChange(async (value) => {
      this.plugin.settings.tagFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Aliases").setHeading();
    containerEl.createEl("p", { text: "Define tag aliases that automatically correct to canonical tags." });
    const aliasesContainer = containerEl.createDiv({ cls: "btm-aliases" });
    this.renderAliases(aliasesContainer);
    new import_obsidian.Setting(containerEl).setName("History").setHeading();
    new import_obsidian.Setting(containerEl).setName("Max History Size").setDesc("Number of operations to keep in history").addSlider((slider) => slider.setLimits(10, 100, 10).setValue(this.plugin.settings.maxHistorySize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxHistorySize = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Orphan Threshold").setDesc("Tags used fewer times than this are considered orphaned").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.orphanThreshold).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.orphanThreshold = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Clear History").setDesc("Remove all operation history").addButton((btn) => btn.setButtonText("Clear").setWarning().onClick(async () => {
      this.plugin.settings.operationHistory = [];
      await this.plugin.saveSettings();
      new import_obsidian.Notice("History cleared.");
    }));
  }
  renderAliases(container) {
    container.empty();
    const aliases = this.plugin.settings.aliases;
    for (const [alias, canonical] of Object.entries(aliases)) {
      new import_obsidian.Setting(container).setName(`#${alias} \u2192 #${canonical}`).addButton((btn) => btn.setIcon("trash").setWarning().onClick(async () => {
        delete this.plugin.settings.aliases[alias];
        await this.plugin.saveSettings();
        this.renderAliases(container);
      }));
    }
    const addRow = container.createDiv({ cls: "btm-add-alias" });
    const aliasInput = new import_obsidian.TextComponent(addRow).setPlaceholder("alias");
    const canonicalInput = new import_obsidian.TextComponent(addRow).setPlaceholder("canonical");
    const addBtn = addRow.createEl("button", { text: "Add" });
    addBtn.onclick = async () => {
      const a = aliasInput.getValue().replace(/^#/, "");
      const c = canonicalInput.getValue().replace(/^#/, "");
      if (a && c) {
        this.plugin.settings.aliases[a] = c;
        await this.plugin.saveSettings();
        this.renderAliases(container);
      }
    };
  }
};
