/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TagLowercasePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  caseStrategy: "lowercase",
  separatorStrategy: "preserve",
  removeSpecialChars: false,
  applyToNestedTags: true,
  aliases: {},
  operationHistory: [],
  scopeFilter: {
    enabled: false,
    includeFolders: [],
    excludeFolders: [],
    filePattern: ""
  },
  orphanThreshold: 2,
  maxHistorySize: 50
};
var TAG_REGEX = /(^|\s)(#[\p{L}\p{N}_\-\/]+)/gu;
var TagLowercasePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.aliasDebounceTimer = null;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("tags", "Bulk Tag Manager", () => {
      new TagManagerModal(this.app, this).open();
    });
    this.addCommand({
      id: "open-tag-manager",
      name: "Open Tag Manager Dashboard",
      callback: () => new TagManagerModal(this.app, this).open()
    });
    this.addCommand({
      id: "convert-all-tags",
      name: "Convert all tags (with preview)",
      callback: () => this.runConversionWithPreview()
    });
    this.addCommand({
      id: "generate-tag-list",
      name: "Generate Tag List",
      callback: () => this.generateTagList()
    });
    this.addCommand({
      id: "show-tag-hierarchy",
      name: "Show Tag Hierarchy",
      callback: () => new TagHierarchyModal(this.app, this).open()
    });
    this.addCommand({
      id: "find-orphan-tags",
      name: "Find Orphaned Tags",
      callback: () => new OrphanTagsModal(this.app, this).open()
    });
    this.addCommand({
      id: "undo-last-operation",
      name: "Undo Last Tag Operation",
      callback: () => this.undoLastOperation()
    });
    this.addSettingTab(new TagLowercaseSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian.TFile && Object.keys(this.settings.aliases).length > 0) {
          this.applyAliasesDebounced(file);
        }
      })
    );
  }
  applyAliasesDebounced(file) {
    if (this.aliasDebounceTimer) clearTimeout(this.aliasDebounceTimer);
    this.aliasDebounceTimer = setTimeout(() => this.applyAliases(file), 1e3);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // --- File Filtering ---
  getFilteredFiles() {
    let files = this.app.vault.getMarkdownFiles();
    if (!this.settings.scopeFilter.enabled) return files;
    const { includeFolders, excludeFolders, filePattern } = this.settings.scopeFilter;
    if (includeFolders.length > 0) {
      files = files.filter((f) => includeFolders.some((folder) => f.path.startsWith(folder)));
    }
    if (excludeFolders.length > 0) {
      files = files.filter((f) => !excludeFolders.some((folder) => f.path.startsWith(folder)));
    }
    if (filePattern) {
      try {
        const regex = new RegExp(filePattern);
        files = files.filter((f) => regex.test(f.path));
      } catch (e) {
      }
    }
    return files;
  }
  // --- History Management ---
  async addToHistory(record) {
    const fullRecord = {
      ...record,
      id: crypto.randomUUID(),
      timestamp: Date.now()
    };
    this.settings.operationHistory.unshift(fullRecord);
    if (this.settings.operationHistory.length > this.settings.maxHistorySize) {
      this.settings.operationHistory = this.settings.operationHistory.slice(0, this.settings.maxHistorySize);
    }
    await this.saveSettings();
  }
  async undoLastOperation() {
    if (this.settings.operationHistory.length === 0) {
      new import_obsidian.Notice("No operations to undo.");
      return;
    }
    const lastOp = this.settings.operationHistory[0];
    let revertedCount = 0;
    new import_obsidian.Notice(`Reverting: ${lastOp.description}...`);
    for (const change of lastOp.changes) {
      const file = this.app.vault.getAbstractFileByPath(change.path);
      if (file instanceof import_obsidian.TFile) {
        try {
          await this.app.vault.modify(file, change.before);
          revertedCount++;
        } catch (e) {
          console.error(`Failed to revert ${change.path}:`, e);
        }
      }
    }
    this.settings.operationHistory.shift();
    await this.saveSettings();
    new import_obsidian.Notice(`Reverted ${revertedCount} files.`);
  }
  // --- Preview System ---
  async previewConversion() {
    const files = this.getFilteredFiles();
    const affectedFiles = [];
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const newContent = this.transformContent(content);
      if (content !== newContent) {
        const changes = this.diffContent(content, newContent);
        affectedFiles.push({ path: file.path, changes, included: true });
      }
    }
    return {
      affectedFiles,
      totalChanges: affectedFiles.reduce((sum, f) => sum + f.changes.length, 0)
    };
  }
  diffContent(before, after) {
    const beforeLines = before.split("\n");
    const afterLines = after.split("\n");
    const changes = [];
    for (let i = 0; i < Math.max(beforeLines.length, afterLines.length); i++) {
      if (beforeLines[i] !== afterLines[i]) {
        changes.push({ line: i + 1, before: beforeLines[i] || "", after: afterLines[i] || "" });
      }
    }
    return changes;
  }
  transformContent(content) {
    const codeBlockRegex = /```[\s\S]*?```|`[^`\n]+`/g;
    const codeBlocks = [];
    let match;
    while ((match = codeBlockRegex.exec(content)) !== null) {
      codeBlocks.push({ start: match.index, end: match.index + match[0].length });
    }
    return content.replace(TAG_REGEX, (fullMatch, prefix, tag, offset) => {
      if (codeBlocks.some((b) => offset >= b.start && offset < b.end)) {
        return fullMatch;
      }
      const clean = tag.substring(1);
      const converted = this.convertTagContent(clean);
      return prefix + "#" + converted;
    });
  }
  async runConversionWithPreview() {
    const preview = await this.previewConversion();
    if (preview.affectedFiles.length === 0) {
      new import_obsidian.Notice("No tags need conversion.");
      return;
    }
    new PreviewModal(this.app, this, preview, async (selectedFiles) => {
      await this.executeConversion(selectedFiles);
    }).open();
  }
  async executeConversion(files) {
    const changes = [];
    let processedCount = 0;
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    for (const previewFile of files) {
      if (!previewFile.included) continue;
      const file = this.app.vault.getAbstractFileByPath(previewFile.path);
      if (!(file instanceof import_obsidian.TFile)) continue;
      try {
        const before = await this.app.vault.read(file);
        await this.processFile(file);
        const after = await this.app.vault.read(file);
        if (before !== after) {
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "convert",
        description: `Bulk conversion (${changes.length} files)`,
        changes
      });
    }
    new import_obsidian.Notice(`Converted tags in ${processedCount} files.`);
  }
  // --- Tag Operations ---
  async runConversion() {
    const files = this.getFilteredFiles();
    const changes = [];
    let processedCount = 0;
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    for (const file of files) {
      try {
        const before = await this.app.vault.read(file);
        await this.processFile(file);
        const after = await this.app.vault.read(file);
        if (before !== after) {
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "convert",
        description: `Bulk conversion (${changes.length} files)`,
        changes
      });
    }
    new import_obsidian.Notice(`Processed ${processedCount} files.`);
  }
  async generateTagList() {
    const tags = this.app.metadataCache.getTags();
    if (!tags || Object.keys(tags).length === 0) {
      new import_obsidian.Notice("No tags found in vault.");
      return;
    }
    const sortedTags = Object.keys(tags).sort((a, b) => a.localeCompare(b));
    const fileContent = `# All Tags

${sortedTags.join("\n")}
`;
    const fileName = "All Tags.md";
    try {
      const existingFile = this.app.vault.getAbstractFileByPath(fileName);
      if (existingFile instanceof import_obsidian.TFile) {
        await this.app.vault.modify(existingFile, fileContent);
      } else {
        await this.app.vault.create(fileName, fileContent);
      }
      new import_obsidian.Notice(`Created "${fileName}" with ${sortedTags.length} tags.`);
    } catch (e) {
      console.error("Failed to create tag list:", e);
      new import_obsidian.Notice("Failed to create tag list file.");
    }
  }
  async renameTag(oldTag, newTag) {
    var _a, _b;
    const files = this.getFilteredFiles();
    const changes = [];
    const search = oldTag.startsWith("#") ? oldTag.substring(1) : oldTag;
    const replace = newTag.startsWith("#") ? newTag.substring(1) : newTag;
    if (!search || !replace) {
      new import_obsidian.Notice("Please provide both old and new tags.");
      return;
    }
    new import_obsidian.Notice(`Scanning for #${search}...`);
    const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const escapedSearch = escapeRegExp(search);
    const tagRegex = new RegExp(`(^|\\s)(#)(${escapedSearch})(?=[\\s\\/]|$|[^\\p{L}\\p{N}_-])`, "gu");
    const matchingFiles = [];
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const cache = this.app.metadataCache.getFileCache(file);
      let hasFrontmatterTag = false;
      if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) {
        const fmTags = Array.isArray(cache.frontmatter.tags) ? cache.frontmatter.tags : [cache.frontmatter.tags];
        hasFrontmatterTag = fmTags.some((t) => {
          const raw = t.startsWith("#") ? t.substring(1) : t;
          return raw === search || raw.startsWith(search + "/");
        });
      }
      if ((_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.tag) {
        const fmTags = Array.isArray(cache.frontmatter.tag) ? cache.frontmatter.tag : [cache.frontmatter.tag];
        hasFrontmatterTag = hasFrontmatterTag || fmTags.some((t) => {
          const raw = t.startsWith("#") ? t.substring(1) : t;
          return raw === search || raw.startsWith(search + "/");
        });
      }
      const hasInlineTag = tagRegex.test(content);
      tagRegex.lastIndex = 0;
      if (hasFrontmatterTag || hasInlineTag) {
        matchingFiles.push(file);
      }
    }
    if (matchingFiles.length === 0) {
      new import_obsidian.Notice(`No files found containing #${search}`);
      return;
    }
    new import_obsidian.Notice(`Found ${matchingFiles.length} files with #${search}. Renaming...`);
    const progressModal = new ProgressModal(this.app, matchingFiles.length);
    progressModal.open();
    let processedCount = 0;
    for (const file of matchingFiles) {
      try {
        const before = await this.app.vault.read(file);
        let modified = false;
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          const processSingleTag = (t) => {
            const hasHash = t.startsWith("#");
            const raw = hasHash ? t.substring(1) : t;
            if (raw === search) {
              modified = true;
              return hasHash ? "#" + replace : replace;
            } else if (raw.startsWith(search + "/")) {
              modified = true;
              const newRaw = replace + raw.substring(search.length);
              return hasHash ? "#" + newRaw : newRaw;
            }
            return t;
          };
          if (fm.tags) {
            if (Array.isArray(fm.tags)) {
              fm.tags = fm.tags.map(processSingleTag);
            } else if (typeof fm.tags === "string") {
              fm.tags = processSingleTag(fm.tags);
            }
          }
          if (fm.tag) {
            if (Array.isArray(fm.tag)) {
              fm.tag = fm.tag.map(processSingleTag);
            } else if (typeof fm.tag === "string") {
              fm.tag = processSingleTag(fm.tag);
            }
          }
        });
        await this.app.vault.process(file, (data) => {
          const newData = data.replace(tagRegex, (m, prefix, hash) => {
            modified = true;
            return prefix + hash + replace;
          });
          tagRegex.lastIndex = 0;
          return newData;
        });
        if (modified) {
          const after = await this.app.vault.read(file);
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
        processedCount++;
        progressModal.update(processedCount);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "rename",
        description: `Rename #${search} \u2192 #${replace}`,
        changes
      });
    }
    new import_obsidian.Notice(`Renamed #${search} \u2192 #${replace} in ${changes.length} files.`);
  }
  async mergeTags(sources, target) {
    const targetClean = target.startsWith("#") ? target.substring(1) : target;
    const sourcesClean = sources.map((s) => s.startsWith("#") ? s.substring(1) : s).filter((s) => s && s !== targetClean);
    if (sourcesClean.length === 0) {
      new import_obsidian.Notice("No valid source tags to merge.");
      return;
    }
    new import_obsidian.Notice(`Merging ${sourcesClean.length} tags into #${targetClean}...`);
    const files = this.getFilteredFiles();
    const changes = [];
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    let processedCount = 0;
    const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const sourcePatterns = sourcesClean.map((s) => escapeRegExp(s)).join("|");
    const tagRegex = new RegExp(`(^|\\s)(#)(${sourcePatterns})(?=[\\s\\/]|$|[^\\p{L}\\p{N}_-])`, "gu");
    for (const file of files) {
      try {
        const before = await this.app.vault.read(file);
        let modified = false;
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          const processSingleTag = (t) => {
            const hasHash = t.startsWith("#");
            const raw = hasHash ? t.substring(1) : t;
            for (const source of sourcesClean) {
              if (raw === source) {
                modified = true;
                return hasHash ? "#" + targetClean : targetClean;
              }
              if (raw.startsWith(source + "/")) {
                modified = true;
                const newRaw = targetClean + raw.substring(source.length);
                return hasHash ? "#" + newRaw : newRaw;
              }
            }
            return t;
          };
          if (fm.tags) {
            if (Array.isArray(fm.tags)) {
              fm.tags = fm.tags.map(processSingleTag);
            } else if (typeof fm.tags === "string") {
              fm.tags = processSingleTag(fm.tags);
            }
          }
          if (fm.tag) {
            if (Array.isArray(fm.tag)) {
              fm.tag = fm.tag.map(processSingleTag);
            } else if (typeof fm.tag === "string") {
              fm.tag = processSingleTag(fm.tag);
            }
          }
        });
        await this.app.vault.process(file, (data) => {
          const newData = data.replace(tagRegex, (match, prefix, hash, capturedTag) => {
            for (const source of sourcesClean) {
              if (capturedTag === source || capturedTag.startsWith(source + "/")) {
                modified = true;
                if (capturedTag === source) {
                  return prefix + hash + targetClean;
                } else {
                  return prefix + hash + targetClean + capturedTag.substring(source.length);
                }
              }
            }
            return match;
          });
          tagRegex.lastIndex = 0;
          return newData;
        });
        if (modified) {
          const after = await this.app.vault.read(file);
          changes.push({ path: file.path, before, after });
        }
        processedCount++;
        progressModal.update(processedCount);
      } catch (e) {
        console.error(`Failed to process ${file.path}:`, e);
        processedCount++;
        progressModal.update(processedCount);
      }
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "merge",
        description: `Merge ${sourcesClean.map((s) => "#" + s).join(", ")} \u2192 #${targetClean}`,
        changes
      });
    }
    new import_obsidian.Notice(`Merged ${sourcesClean.length} tags into #${targetClean}. ${changes.length} files changed.`);
  }
  async batchRename(pattern, replacement) {
    const files = this.getFilteredFiles();
    const changes = [];
    let regex;
    try {
      regex = new RegExp(pattern, "g");
    } catch (e) {
      new import_obsidian.Notice("Invalid regex pattern.");
      return;
    }
    const progressModal = new ProgressModal(this.app, files.length);
    progressModal.open();
    let processedCount = 0;
    for (const file of files) {
      const before = await this.app.vault.read(file);
      await this.app.vault.process(file, (data) => {
        return data.replace(TAG_REGEX, (fullMatch, prefix, tag) => {
          const clean = tag.substring(1);
          const newTag = clean.replace(regex, replacement);
          if (newTag !== clean) {
            return prefix + "#" + newTag;
          }
          return fullMatch;
        });
      });
      const after = await this.app.vault.read(file);
      if (before !== after) {
        changes.push({ path: file.path, before, after });
      }
      processedCount++;
      progressModal.update(processedCount);
    }
    progressModal.close();
    if (changes.length > 0) {
      await this.addToHistory({
        type: "pattern",
        description: `Pattern: /${pattern}/ \u2192 ${replacement}`,
        changes
      });
    }
    new import_obsidian.Notice(`Pattern rename affected ${changes.length} files.`);
  }
  // --- Tag Analysis ---
  getTagHierarchy() {
    const tags = this.app.metadataCache.getTags() || {};
    const root = [];
    for (const [tag, count] of Object.entries(tags)) {
      const parts = tag.substring(1).split("/");
      let currentLevel = root;
      let currentPath = "";
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        currentPath = currentPath ? `${currentPath}/${part}` : part;
        let existingNode = currentLevel.find((n) => n.name === part);
        if (!existingNode) {
          existingNode = { name: part, fullPath: currentPath, count: 0, children: [] };
          currentLevel.push(existingNode);
        }
        if (i === parts.length - 1) {
          existingNode.count = count;
        }
        currentLevel = existingNode.children;
      }
    }
    return root;
  }
  findOrphanedTags() {
    const tags = this.app.metadataCache.getTags() || {};
    return Object.entries(tags).filter(([, count]) => count < this.settings.orphanThreshold).map(([tag, count]) => ({ tag, count })).sort((a, b) => a.count - b.count);
  }
  analyzeTagStandardization() {
    const tags = Object.keys(this.app.metadataCache.getTags() || {});
    const totalTags = tags.length;
    if (totalTags === 0) {
      return {
        totalTags: 0,
        caseStats: { lowercase: 0, uppercase: 0, mixed: 0, consistency: 100 },
        separatorStats: { underscore: 0, hyphen: 0, both: 0, none: 0, consistency: 100 },
        specialCharStats: { withSpecial: 0, clean: 0, consistency: 100 },
        nestingStats: { nested: 0, flat: 0, maxDepth: 0 },
        lengthStats: { short: 0, medium: 0, long: 0, avgLength: 0 }
      };
    }
    let lowercase = 0, uppercase = 0, mixedCase = 0;
    let underscore = 0, hyphen = 0, bothSeparators = 0, noSeparator = 0;
    let withSpecial = 0, clean = 0;
    let nested = 0, flat = 0;
    let maxDepth = 0;
    let short = 0, medium = 0, long = 0;
    let totalLength = 0;
    for (const tag of tags) {
      const rawTag = tag.startsWith("#") ? tag.substring(1) : tag;
      const letters = rawTag.replace(/[^a-zA-Z]/g, "");
      if (letters.length > 0) {
        const isAllLower = letters === letters.toLowerCase();
        const isAllUpper = letters === letters.toUpperCase();
        if (isAllLower && !isAllUpper) lowercase++;
        else if (isAllUpper && !isAllLower) uppercase++;
        else mixedCase++;
      } else {
        lowercase++;
      }
      const hasUnderscore = rawTag.includes("_");
      const hasHyphen = rawTag.includes("-");
      if (hasUnderscore && hasHyphen) bothSeparators++;
      else if (hasUnderscore) underscore++;
      else if (hasHyphen) hyphen++;
      else noSeparator++;
      const hasSpecial = /[^a-zA-Z0-9_\-\/]/.test(rawTag);
      if (hasSpecial) withSpecial++;
      else clean++;
      const depth = (rawTag.match(/\//g) || []).length + 1;
      if (depth > 1) nested++;
      else flat++;
      maxDepth = Math.max(maxDepth, depth);
      totalLength += rawTag.length;
      if (rawTag.length <= 10) short++;
      else if (rawTag.length <= 25) medium++;
      else long++;
    }
    const dominantCase = Math.max(lowercase, uppercase, mixedCase);
    const caseConsistency = totalTags > 0 ? Math.round(dominantCase / totalTags * 100) : 100;
    const separatorCounts = [underscore, hyphen, noSeparator];
    const dominantSeparator = Math.max(...separatorCounts);
    const separatorConsistency = totalTags > 0 ? Math.round((dominantSeparator + (bothSeparators === 0 ? 0 : 0)) / totalTags * 100) : 100;
    const specialConsistency = totalTags > 0 ? Math.round(clean / totalTags * 100) : 100;
    return {
      totalTags,
      caseStats: {
        lowercase,
        uppercase,
        mixed: mixedCase,
        consistency: caseConsistency
      },
      separatorStats: {
        underscore,
        hyphen,
        both: bothSeparators,
        none: noSeparator,
        consistency: separatorConsistency
      },
      specialCharStats: {
        withSpecial,
        clean,
        consistency: specialConsistency
      },
      nestingStats: {
        nested,
        flat,
        maxDepth
      },
      lengthStats: {
        short,
        medium,
        long,
        avgLength: Math.round(totalLength / totalTags)
      }
    };
  }
  // --- Aliases ---
  async applyAliases(file) {
    const aliases = this.settings.aliases;
    if (Object.keys(aliases).length === 0) return;
    let modified = false;
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const processSingleTag = (t) => {
        const hasHash = t.startsWith("#");
        const raw = hasHash ? t.substring(1) : t;
        if (aliases[raw]) {
          modified = true;
          return hasHash ? "#" + aliases[raw] : aliases[raw];
        }
        return t;
      };
      if (fm.tags) {
        fm.tags = Array.isArray(fm.tags) ? fm.tags.map(processSingleTag) : processSingleTag(fm.tags);
      }
      if (fm.tag) {
        fm.tag = Array.isArray(fm.tag) ? fm.tag.map(processSingleTag) : processSingleTag(fm.tag);
      }
    });
    if (modified) {
      for (const [alias, canonical] of Object.entries(aliases)) {
        const escapeRegExp = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
        const regex = new RegExp(`(^|\\s)(#)(${escapeRegExp(alias)})(?=[\\s\\/]|$)`, "gu");
        await this.app.vault.process(
          file,
          (data) => data.replace(regex, (m, prefix, hash) => prefix + hash + canonical)
        );
      }
    }
  }
  // --- Core Processing ---
  async processFile(file) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      const processSingleTag = (t) => {
        const hasHash = t.startsWith("#");
        const clean = hasHash ? t.substring(1) : t;
        const converted = this.convertTagContent(clean);
        return hasHash ? "#" + converted : converted;
      };
      if (fm.tags) {
        fm.tags = Array.isArray(fm.tags) ? fm.tags.map(processSingleTag) : processSingleTag(fm.tags);
      }
      if (fm.tag) {
        fm.tag = Array.isArray(fm.tag) ? fm.tag.map(processSingleTag) : processSingleTag(fm.tag);
      }
    });
    await this.app.vault.process(file, (data) => this.transformContent(data));
  }
  convertTagContent(tagContent) {
    const parts = tagContent.split("/");
    const processedParts = parts.map((part, index) => {
      if (index > 0 && !this.settings.applyToNestedTags) return part;
      return this.transformSegment(part);
    });
    return processedParts.join("/");
  }
  transformSegment(segment) {
    let s = segment;
    if (this.settings.removeSpecialChars) {
      s = s.replace(/[^\p{L}\p{N}\-_]/gu, "");
    }
    if (this.settings.separatorStrategy === "snake") {
      s = s.replace(/-/g, "_");
    } else if (this.settings.separatorStrategy === "kebab") {
      s = s.replace(/_/g, "-");
    }
    if (this.settings.caseStrategy === "lowercase") {
      s = s.toLowerCase();
    } else if (this.settings.caseStrategy === "uppercase") {
      s = s.toUpperCase();
    }
    return s;
  }
  getAllTags() {
    const tags = this.app.metadataCache.getTags() || {};
    return Object.keys(tags).map((t) => t.substring(1)).sort();
  }
};
var ProgressModal = class extends import_obsidian.Modal {
  constructor(app, total) {
    super(app);
    this.total = total;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-progress-modal");
    new import_obsidian.Setting(contentEl).setName("Processing...").setHeading();
    const container = contentEl.createDiv({ cls: "btm-progress-container" });
    this.progressBar = container.createDiv({ cls: "btm-progress-bar" });
    this.progressBar.createDiv({ cls: "btm-progress-fill" });
    this.progressText = contentEl.createDiv({ cls: "btm-progress-text", text: `0 / ${this.total}` });
  }
  update(current) {
    const percent = Math.round(current / this.total * 100);
    const fill = this.progressBar.querySelector(".btm-progress-fill");
    if (fill) fill.style.width = `${percent}%`;
    this.progressText.textContent = `${current} / ${this.total} (${percent}%)`;
  }
  onClose() {
    this.contentEl.empty();
  }
};
var PreviewModal = class extends import_obsidian.Modal {
  constructor(app, plugin, preview, onConfirm) {
    super(app);
    this.plugin = plugin;
    this.preview = preview;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-preview-modal");
    new import_obsidian.Setting(contentEl).setName("Preview Changes").setHeading();
    contentEl.createEl("p", { text: `${this.preview.affectedFiles.length} files will be modified (${this.preview.totalChanges} changes)` });
    const listEl = contentEl.createDiv({ cls: "btm-preview-list" });
    for (const file of this.preview.affectedFiles) {
      const fileEl = listEl.createDiv({ cls: "btm-preview-file" });
      const headerEl = fileEl.createDiv({ cls: "btm-preview-file-header" });
      const checkbox = headerEl.createEl("input", { type: "checkbox" });
      checkbox.checked = file.included;
      checkbox.addEventListener("change", () => {
        file.included = checkbox.checked;
      });
      headerEl.createSpan({ text: file.path, cls: "btm-preview-file-path" });
      headerEl.createSpan({ text: ` (${file.changes.length} changes)`, cls: "btm-preview-file-count" });
      const changesEl = fileEl.createDiv({ cls: "btm-preview-changes" });
      for (const change of file.changes.slice(0, 5)) {
        const changeEl = changesEl.createDiv({ cls: "btm-preview-change" });
        changeEl.createDiv({ cls: "btm-diff-remove", text: `L${change.line}: ${change.before}` });
        changeEl.createDiv({ cls: "btm-diff-add", text: `L${change.line}: ${change.after}` });
      }
      if (file.changes.length > 5) {
        changesEl.createDiv({ text: `... and ${file.changes.length - 5} more`, cls: "btm-more" });
      }
    }
    const btnContainer = contentEl.createDiv({ cls: "btm-button-row" });
    const selectAllBtn = btnContainer.createEl("button", { text: "Select All" });
    selectAllBtn.onclick = () => {
      this.preview.affectedFiles.forEach((f) => f.included = true);
      listEl.querySelectorAll('input[type="checkbox"]').forEach((cb) => cb.checked = true);
    };
    const selectNoneBtn = btnContainer.createEl("button", { text: "Select None" });
    selectNoneBtn.onclick = () => {
      this.preview.affectedFiles.forEach((f) => f.included = false);
      listEl.querySelectorAll('input[type="checkbox"]').forEach((cb) => cb.checked = false);
    };
    const cancelBtn = btnContainer.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = btnContainer.createEl("button", { text: "Apply Changes", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.close();
      this.onConfirm(this.preview.affectedFiles.filter((f) => f.included));
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};
var HistoryModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-history-modal");
    new import_obsidian.Setting(contentEl).setName("Operation History").setHeading();
    if (this.plugin.settings.operationHistory.length === 0) {
      contentEl.createEl("p", { text: "No operations recorded yet." });
      return;
    }
    const listEl = contentEl.createDiv({ cls: "btm-history-list" });
    for (const op of this.plugin.settings.operationHistory) {
      const itemEl = listEl.createDiv({ cls: "btm-history-item" });
      const date = new Date(op.timestamp);
      const timeStr = date.toLocaleDateString() + " " + date.toLocaleTimeString();
      itemEl.createDiv({ cls: "btm-history-time", text: timeStr });
      itemEl.createDiv({ cls: "btm-history-desc", text: op.description });
      itemEl.createDiv({ cls: "btm-history-files", text: `${op.changes.length} files affected` });
      if (op === this.plugin.settings.operationHistory[0]) {
        const revertBtn = itemEl.createEl("button", { text: "Undo", cls: "btm-revert-btn" });
        revertBtn.onclick = async () => {
          this.close();
          await this.plugin.undoLastOperation();
        };
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagHierarchyModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-hierarchy-modal");
    new import_obsidian.Setting(contentEl).setName("Tag Hierarchy").setHeading();
    const hierarchy = this.plugin.getTagHierarchy();
    if (hierarchy.length === 0) {
      contentEl.createEl("p", { text: "No tags found." });
      return;
    }
    const treeEl = contentEl.createDiv({ cls: "btm-tree" });
    this.renderTree(treeEl, hierarchy, 0);
  }
  renderTree(container, nodes, depth) {
    for (const node of nodes.sort((a, b) => a.name.localeCompare(b.name))) {
      const nodeEl = container.createDiv({ cls: "btm-tree-node" });
      nodeEl.style.paddingLeft = `${depth * 20}px`;
      const hasChildren = node.children.length > 0;
      const headerEl = nodeEl.createDiv({ cls: "btm-tree-header" });
      const iconEl = headerEl.createSpan({ cls: "btm-tree-icon" });
      (0, import_obsidian.setIcon)(iconEl, hasChildren ? "folder" : "tag");
      headerEl.createSpan({ text: node.name, cls: "btm-tree-name" });
      if (node.count > 0) {
        headerEl.createSpan({ text: ` (${node.count})`, cls: "btm-tree-count" });
      }
      if (hasChildren) {
        const childContainer = container.createDiv({ cls: "btm-tree-children" });
        this.renderTree(childContainer, node.children, depth + 1);
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var OrphanTagsModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-orphan-modal");
    new import_obsidian.Setting(contentEl).setName("Orphaned Tags").setDesc(`Tags used in fewer than ${this.plugin.settings.orphanThreshold} files`).setHeading();
    const orphans = this.plugin.findOrphanedTags();
    if (orphans.length === 0) {
      contentEl.createEl("p", { text: "No orphaned tags found!" });
      return;
    }
    contentEl.createEl("p", { text: `Found ${orphans.length} orphaned tags:` });
    const listEl = contentEl.createDiv({ cls: "btm-orphan-list" });
    for (const { tag, count } of orphans) {
      const itemEl = listEl.createDiv({ cls: "btm-orphan-item" });
      itemEl.createSpan({ text: tag, cls: "btm-orphan-tag" });
      itemEl.createSpan({ text: ` (${count} use${count === 1 ? "" : "s"})`, cls: "btm-orphan-count" });
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagSuggest = class extends import_obsidian.SuggestModal {
  constructor(app, plugin, onSelect) {
    super(app);
    this.plugin = plugin;
    this.onSelect = onSelect;
    this.tagCounts = this.plugin.app.metadataCache.getTags() || {};
  }
  getSuggestions(query) {
    const tags = this.plugin.getAllTags();
    if (!query) return tags.slice(0, 50);
    return tags.filter((t) => t.toLowerCase().includes(query.toLowerCase())).slice(0, 50);
  }
  renderSuggestion(tag, el) {
    const count = this.tagCounts["#" + tag] || 0;
    el.createSpan({ text: `#${tag}`, cls: "btm-suggest-tag" });
    el.createSpan({ text: ` (${count})`, cls: "btm-suggest-count" });
  }
  onChooseSuggestion(tag) {
    this.onSelect(tag);
  }
};
var MultiTagSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, onConfirm) {
    super(app);
    this.selectedTags = /* @__PURE__ */ new Set();
    this.plugin = plugin;
    this.onConfirm = onConfirm;
    this.tagCounts = this.plugin.app.metadataCache.getTags() || {};
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-multiselect-modal");
    new import_obsidian.Setting(contentEl).setName("Select Tags to Merge").setHeading();
    const searchDiv = contentEl.createDiv({ cls: "btm-search-container" });
    this.searchInput = new import_obsidian.TextComponent(searchDiv).setPlaceholder("Search tags...");
    this.searchInput.inputEl.addEventListener("input", () => this.renderList());
    const selectedDiv = contentEl.createDiv({ cls: "btm-selected-tags" });
    selectedDiv.id = "btm-selected-display";
    this.listEl = contentEl.createDiv({ cls: "btm-tag-list" });
    this.renderList();
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = btnRow.createEl("button", { text: "Confirm Selection", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.close();
      this.onConfirm(Array.from(this.selectedTags));
    };
  }
  renderList() {
    this.listEl.empty();
    const query = this.searchInput.getValue().toLowerCase();
    const tags = this.plugin.getAllTags();
    const filtered = query ? tags.filter((t) => t.toLowerCase().includes(query)) : tags;
    for (const tag of filtered.slice(0, 100)) {
      const count = this.tagCounts["#" + tag] || 0;
      const itemEl = this.listEl.createDiv({ cls: "btm-tag-item" });
      const checkbox = itemEl.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedTags.has(tag);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedTags.add(tag);
        } else {
          this.selectedTags.delete(tag);
        }
        this.updateSelectedDisplay();
      });
      itemEl.createSpan({ text: `#${tag}`, cls: "btm-tag-name" });
      itemEl.createSpan({ text: ` (${count})`, cls: "btm-tag-count" });
    }
    this.updateSelectedDisplay();
  }
  updateSelectedDisplay() {
    const display = this.contentEl.querySelector("#btm-selected-display");
    if (display) {
      display.empty();
      if (this.selectedTags.size > 0) {
        display.createSpan({ text: `Selected (${this.selectedTags.size}): ` });
        display.createSpan({ text: Array.from(this.selectedTags).map((t) => "#" + t).join(", "), cls: "btm-selected-list" });
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var FolderSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, currentFolders, onConfirm) {
    super(app);
    this.plugin = plugin;
    this.selectedFolders = new Set(currentFolders.filter((f) => f));
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-folder-modal");
    new import_obsidian.Setting(contentEl).setName("Select Folders").setHeading();
    const searchDiv = contentEl.createDiv({ cls: "btm-search-container" });
    this.searchInput = new import_obsidian.TextComponent(searchDiv).setPlaceholder("Search folders...");
    this.searchInput.inputEl.addEventListener("input", () => this.renderList());
    const selectedDiv = contentEl.createDiv({ cls: "btm-selected-tags" });
    selectedDiv.id = "btm-selected-folders-display";
    this.listEl = contentEl.createDiv({ cls: "btm-tag-list" });
    this.renderList();
    const btnRow = contentEl.createDiv({ cls: "btm-button-row" });
    const cancelBtn = btnRow.createEl("button", { text: "Cancel" });
    cancelBtn.onclick = () => this.close();
    const confirmBtn = btnRow.createEl("button", { text: "Confirm Selection", cls: "mod-cta" });
    confirmBtn.onclick = () => {
      this.close();
      this.onConfirm(Array.from(this.selectedFolders));
    };
  }
  getAllFolders() {
    const folders = [];
    const collectFolders = (folder) => {
      if (folder.path && folder.path !== "/") {
        folders.push(folder.path);
      }
      for (const child of folder.children) {
        if (child instanceof import_obsidian.TFolder) {
          collectFolders(child);
        }
      }
    };
    collectFolders(this.app.vault.getRoot());
    return folders.sort();
  }
  renderList() {
    this.listEl.empty();
    const query = this.searchInput.getValue().toLowerCase();
    const folders = this.getAllFolders();
    const filtered = query ? folders.filter((f) => f.toLowerCase().includes(query)) : folders;
    if (filtered.length === 0) {
      this.listEl.createEl("p", { text: "No folders found", cls: "btm-no-results" });
      return;
    }
    for (const folder of filtered.slice(0, 100)) {
      const itemEl = this.listEl.createDiv({ cls: "btm-tag-item" });
      const checkbox = itemEl.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedFolders.has(folder);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedFolders.add(folder);
        } else {
          this.selectedFolders.delete(folder);
        }
        this.updateSelectedDisplay();
      });
      const folderIcon = itemEl.createSpan({ cls: "btm-icon" });
      (0, import_obsidian.setIcon)(folderIcon, "folder");
      itemEl.createSpan({ text: " " + folder, cls: "btm-folder-name" });
    }
    this.updateSelectedDisplay();
  }
  updateSelectedDisplay() {
    const display = this.contentEl.querySelector("#btm-selected-folders-display");
    if (display) {
      display.empty();
      if (this.selectedFolders.size > 0) {
        display.createSpan({ text: `Selected (${this.selectedFolders.size}): ` });
        display.createSpan({ text: Array.from(this.selectedFolders).join(", "), cls: "btm-selected-list" });
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagManagerModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("btm-dashboard");
    new import_obsidian.Setting(contentEl).setName("Bulk Tag Manager").setHeading();
    this.statsEl = contentEl.createDiv({ cls: "btm-stats" });
    this.updateStats();
    contentEl.createEl("hr");
    new import_obsidian.Setting(contentEl).setName("Rename Tag").setHeading();
    const renameContainer = contentEl.createDiv({ cls: "btm-input-row" });
    const findDiv = renameContainer.createDiv({ cls: "btm-input-group" });
    findDiv.createEl("label", { text: "Find" });
    this.findInput = new import_obsidian.TextComponent(findDiv).setPlaceholder("#old-tag");
    const findSuggestBtn = findDiv.createEl("button", { cls: "btm-suggest-btn btm-icon-btn" });
    (0, import_obsidian.setIcon)(findSuggestBtn, "search");
    const tagCountDisplay = findDiv.createDiv({ cls: "btm-tag-count-display" });
    findSuggestBtn.onclick = () => new TagSuggest(this.app, this.plugin, (t) => {
      this.findInput.setValue(t);
      const tags = this.plugin.app.metadataCache.getTags() || {};
      const count = tags["#" + t] || 0;
      tagCountDisplay.textContent = `${count} occurrence${count === 1 ? "" : "s"}`;
    }).open();
    const replaceDiv = renameContainer.createDiv({ cls: "btm-input-group" });
    replaceDiv.createEl("label", { text: "Replace" });
    this.replaceInput = new import_obsidian.TextComponent(replaceDiv).setPlaceholder("#new-tag");
    const btnRename = renameContainer.createEl("button", { text: "Rename", cls: "mod-cta" });
    btnRename.onclick = async () => {
      const oldT = this.findInput.getValue();
      const newT = this.replaceInput.getValue();
      if (oldT && newT) {
        this.close();
        await this.plugin.renameTag(oldT, newT);
      } else {
        new import_obsidian.Notice("Please fill both fields.");
      }
    };
    contentEl.createEl("hr");
    new import_obsidian.Setting(contentEl).setName("Merge Tags").setDesc("Combine multiple tags into one").setHeading();
    const mergeContainer = contentEl.createDiv({ cls: "btm-input-row" });
    const sourcesDiv = mergeContainer.createDiv({ cls: "btm-input-group btm-wide" });
    sourcesDiv.createEl("label", { text: "Source tags" });
    this.mergeSourcesInput = new import_obsidian.TextComponent(sourcesDiv).setPlaceholder("#tag1, #tag2, #tag3");
    const selectTagsBtn = sourcesDiv.createEl("button", { cls: "btm-suggest-btn btm-icon-btn" });
    (0, import_obsidian.setIcon)(selectTagsBtn, "list-filter");
    selectTagsBtn.createSpan({ text: " Select" });
    selectTagsBtn.onclick = () => new MultiTagSelectModal(this.app, this.plugin, (tags) => {
      this.mergeSourcesInput.setValue(tags.map((t) => "#" + t).join(", "));
    }).open();
    const targetDiv = mergeContainer.createDiv({ cls: "btm-input-group" });
    targetDiv.createEl("label", { text: "Target" });
    this.mergeTargetInput = new import_obsidian.TextComponent(targetDiv).setPlaceholder("#merged");
    const targetSuggestBtn = targetDiv.createEl("button", { cls: "btm-suggest-btn btm-icon-btn" });
    (0, import_obsidian.setIcon)(targetSuggestBtn, "search");
    targetSuggestBtn.onclick = () => new TagSuggest(this.app, this.plugin, (t) => this.mergeTargetInput.setValue(t)).open();
    const btnMerge = mergeContainer.createEl("button", { text: "Merge", cls: "mod-cta" });
    btnMerge.onclick = async () => {
      const sources = this.mergeSourcesInput.getValue().split(",").map((s) => s.trim()).filter((s) => s);
      const target = this.mergeTargetInput.getValue().trim();
      if (sources.length > 0 && target) {
        this.close();
        await this.plugin.mergeTags(sources, target);
      } else {
        new import_obsidian.Notice("Please provide source tags and a target.");
      }
    };
    contentEl.createEl("hr");
    new import_obsidian.Setting(contentEl).setName("Pattern Rename").setDesc("Use regex to rename tags").setHeading();
    const patternContainer = contentEl.createDiv({ cls: "btm-input-row" });
    const patternDiv = patternContainer.createDiv({ cls: "btm-input-group" });
    patternDiv.createEl("label", { text: "Pattern (regex)" });
    this.patternInput = new import_obsidian.TextComponent(patternDiv).setPlaceholder("^old-(.*)");
    const patternReplaceDiv = patternContainer.createDiv({ cls: "btm-input-group" });
    patternReplaceDiv.createEl("label", { text: "Replacement" });
    this.patternReplaceInput = new import_obsidian.TextComponent(patternReplaceDiv).setPlaceholder("new-$1");
    const btnPattern = patternContainer.createEl("button", { text: "Apply", cls: "mod-cta" });
    btnPattern.onclick = async () => {
      const pattern = this.patternInput.getValue();
      const replacement = this.patternReplaceInput.getValue();
      if (pattern) {
        this.close();
        await this.plugin.batchRename(pattern, replacement);
      } else {
        new import_obsidian.Notice("Please provide a pattern.");
      }
    };
    contentEl.createEl("hr");
    new import_obsidian.Setting(contentEl).setName("Bulk Conversion Settings").setHeading();
    new import_obsidian.Setting(contentEl).setName("Case Strategy").addDropdown((dropdown) => dropdown.addOption("lowercase", "Lowercase").addOption("uppercase", "Uppercase").addOption("none", "No Change").setValue(this.plugin.settings.caseStrategy).onChange(async (value) => {
      this.plugin.settings.caseStrategy = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    new import_obsidian.Setting(contentEl).setName("Separator Style").addDropdown((dropdown) => dropdown.addOption("preserve", "Preserve").addOption("snake", "Snake Case (- \u2192 _)").addOption("kebab", "Kebab Case (_ \u2192 -)").setValue(this.plugin.settings.separatorStrategy).onChange(async (value) => {
      this.plugin.settings.separatorStrategy = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    new import_obsidian.Setting(contentEl).setName("Remove Special Characters").addToggle((toggle) => toggle.setValue(this.plugin.settings.removeSpecialChars).onChange(async (value) => {
      this.plugin.settings.removeSpecialChars = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    new import_obsidian.Setting(contentEl).setName("Apply to Nested Tags").addToggle((toggle) => toggle.setValue(this.plugin.settings.applyToNestedTags).onChange(async (value) => {
      this.plugin.settings.applyToNestedTags = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    contentEl.createEl("hr");
    new import_obsidian.Setting(contentEl).setName("Scope Filter").setHeading();
    new import_obsidian.Setting(contentEl).setName("Enable Scope Filter").setDesc("Limit operations to specific folders").addToggle((toggle) => toggle.setValue(this.plugin.settings.scopeFilter.enabled).onChange(async (value) => {
      this.plugin.settings.scopeFilter.enabled = value;
      await this.plugin.saveSettings();
      this.updateStats();
    }));
    const includeContainer = contentEl.createDiv({ cls: "btm-scope-row" });
    includeContainer.createEl("label", { text: "Include Folders:" });
    const includeDisplay = includeContainer.createDiv({ cls: "btm-folder-display" });
    includeDisplay.textContent = this.plugin.settings.scopeFilter.includeFolders.join(", ") || "(all folders)";
    const includeBtn = includeContainer.createEl("button", { cls: "btm-suggest-btn btm-icon-btn" });
    (0, import_obsidian.setIcon)(includeBtn, "folder-plus");
    includeBtn.createSpan({ text: " Select" });
    includeBtn.onclick = () => new FolderSelectModal(
      this.app,
      this.plugin,
      this.plugin.settings.scopeFilter.includeFolders,
      async (folders) => {
        this.plugin.settings.scopeFilter.includeFolders = folders;
        await this.plugin.saveSettings();
        includeDisplay.textContent = folders.join(", ") || "(all folders)";
        this.updateStats();
      }
    ).open();
    const excludeContainer = contentEl.createDiv({ cls: "btm-scope-row" });
    excludeContainer.createEl("label", { text: "Exclude Folders:" });
    const excludeDisplay = excludeContainer.createDiv({ cls: "btm-folder-display" });
    excludeDisplay.textContent = this.plugin.settings.scopeFilter.excludeFolders.join(", ") || "(none)";
    const excludeBtn = excludeContainer.createEl("button", { cls: "btm-suggest-btn btm-icon-btn" });
    (0, import_obsidian.setIcon)(excludeBtn, "folder-minus");
    excludeBtn.createSpan({ text: " Select" });
    excludeBtn.onclick = () => new FolderSelectModal(
      this.app,
      this.plugin,
      this.plugin.settings.scopeFilter.excludeFolders,
      async (folders) => {
        this.plugin.settings.scopeFilter.excludeFolders = folders;
        await this.plugin.saveSettings();
        excludeDisplay.textContent = folders.join(", ") || "(none)";
        this.updateStats();
      }
    ).open();
    contentEl.createEl("hr");
    const actionRow = contentEl.createDiv({ cls: "btm-action-row" });
    const btnConvert = this.createIconButton(actionRow, "refresh-cw", "Convert All", "mod-cta");
    btnConvert.onclick = async () => {
      this.close();
      await this.plugin.runConversionWithPreview();
    };
    const btnList = this.createIconButton(actionRow, "list", "Tag List");
    btnList.onclick = async () => {
      this.close();
      await this.plugin.generateTagList();
    };
    const btnHierarchy = this.createIconButton(actionRow, "git-branch", "Hierarchy");
    btnHierarchy.onclick = () => {
      this.close();
      new TagHierarchyModal(this.app, this.plugin).open();
    };
    const btnOrphans = this.createIconButton(actionRow, "alert-circle", "Orphans");
    btnOrphans.onclick = () => {
      this.close();
      new OrphanTagsModal(this.app, this.plugin).open();
    };
    const btnHistory = this.createIconButton(actionRow, "history", "History");
    btnHistory.onclick = () => {
      this.close();
      new HistoryModal(this.app, this.plugin).open();
    };
  }
  createIconButton(container, iconName, text, cls = "") {
    const btn = container.createEl("button", { cls: `btm-icon-btn ${cls}`.trim() });
    const iconEl = btn.createSpan({ cls: "btm-btn-icon" });
    (0, import_obsidian.setIcon)(iconEl, iconName);
    btn.createSpan({ text: " " + text });
    return btn;
  }
  updateStats() {
    this.statsEl.empty();
    this.statsEl.addClass("btm-standardization-panel");
    const stats = this.plugin.analyzeTagStandardization();
    const files = this.plugin.getFilteredFiles();
    const headerRow = this.statsEl.createDiv({ cls: "btm-stats-header" });
    const tagsItem = headerRow.createSpan({ cls: "btm-stat-item" });
    (0, import_obsidian.setIcon)(tagsItem.createSpan({ cls: "btm-stat-icon" }), "tags");
    tagsItem.createSpan({ text: ` ${stats.totalTags} tags` });
    const filesItem = headerRow.createSpan({ cls: "btm-stat-item" });
    (0, import_obsidian.setIcon)(filesItem.createSpan({ cls: "btm-stat-icon" }), "files");
    filesItem.createSpan({ text: ` ${files.length} files` });
    const metricsGrid = this.statsEl.createDiv({ cls: "btm-metrics-grid" });
    const caseBox = metricsGrid.createDiv({ cls: "btm-metric-box" });
    caseBox.createDiv({ text: "Case", cls: "btm-metric-label" });
    this.createProgressBar(caseBox, stats.caseStats.consistency);
    const caseDetails = caseBox.createDiv({ cls: "btm-metric-details" });
    if (stats.caseStats.lowercase > 0) caseDetails.createSpan({ text: `${stats.caseStats.lowercase} lower` });
    if (stats.caseStats.uppercase > 0) caseDetails.createSpan({ text: `${stats.caseStats.uppercase} UPPER` });
    if (stats.caseStats.mixed > 0) caseDetails.createSpan({ text: `${stats.caseStats.mixed} Mixed` });
    const sepBox = metricsGrid.createDiv({ cls: "btm-metric-box" });
    sepBox.createDiv({ text: "Separators", cls: "btm-metric-label" });
    this.createProgressBar(sepBox, stats.separatorStats.consistency);
    const sepDetails = sepBox.createDiv({ cls: "btm-metric-details" });
    if (stats.separatorStats.hyphen > 0) sepDetails.createSpan({ text: `${stats.separatorStats.hyphen} kebab-case` });
    if (stats.separatorStats.underscore > 0) sepDetails.createSpan({ text: `${stats.separatorStats.underscore} snake_case` });
    if (stats.separatorStats.both > 0) sepDetails.createSpan({ text: `${stats.separatorStats.both} mixed` });
    if (stats.separatorStats.none > 0) sepDetails.createSpan({ text: `${stats.separatorStats.none} none` });
    const specialBox = metricsGrid.createDiv({ cls: "btm-metric-box" });
    specialBox.createDiv({ text: "Clean Tags", cls: "btm-metric-label" });
    this.createProgressBar(specialBox, stats.specialCharStats.consistency);
    const specialDetails = specialBox.createDiv({ cls: "btm-metric-details" });
    specialDetails.createSpan({ text: `${stats.specialCharStats.clean} clean` });
    if (stats.specialCharStats.withSpecial > 0) {
      specialDetails.createSpan({ text: `${stats.specialCharStats.withSpecial} with special chars` });
    }
    const nestBox = metricsGrid.createDiv({ cls: "btm-metric-box" });
    nestBox.createDiv({ text: "Structure", cls: "btm-metric-label" });
    const nestDetails = nestBox.createDiv({ cls: "btm-metric-details" });
    nestDetails.createSpan({ text: `${stats.nestingStats.flat} flat` });
    nestDetails.createSpan({ text: `${stats.nestingStats.nested} nested` });
    if (stats.nestingStats.maxDepth > 1) {
      nestDetails.createSpan({ text: `max depth: ${stats.nestingStats.maxDepth}` });
    }
    const lengthBox = metricsGrid.createDiv({ cls: "btm-metric-box" });
    lengthBox.createDiv({ text: "Length", cls: "btm-metric-label" });
    const lengthDetails = lengthBox.createDiv({ cls: "btm-metric-details" });
    lengthDetails.createSpan({ text: `avg: ${stats.lengthStats.avgLength} chars` });
    if (stats.lengthStats.long > 0) {
      lengthDetails.createSpan({ text: `${stats.lengthStats.long} long (>25)` });
    }
  }
  createProgressBar(container, percentage) {
    const barContainer = container.createDiv({ cls: "btm-progress-container" });
    const bar = barContainer.createDiv({ cls: "btm-progress-bar" });
    bar.style.width = `${percentage}%`;
    if (percentage >= 90) bar.addClass("btm-progress-good");
    else if (percentage >= 70) bar.addClass("btm-progress-ok");
    else bar.addClass("btm-progress-warn");
    barContainer.createSpan({ text: `${percentage}%`, cls: "btm-progress-label" });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var TagLowercaseSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Bulk Tag Manager Settings").setHeading();
    containerEl.createEl("p", { text: "Access the full dashboard via the ribbon icon or command palette." });
    new import_obsidian.Setting(containerEl).setName("Case Strategy").addDropdown((dropdown) => dropdown.addOption("lowercase", "Lowercase").addOption("uppercase", "Uppercase").addOption("none", "No Change").setValue(this.plugin.settings.caseStrategy).onChange(async (value) => {
      this.plugin.settings.caseStrategy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Separator Style").addDropdown((dropdown) => dropdown.addOption("preserve", "Preserve").addOption("snake", "Snake Case").addOption("kebab", "Kebab Case").setValue(this.plugin.settings.separatorStrategy).onChange(async (value) => {
      this.plugin.settings.separatorStrategy = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Remove Special Characters").addToggle((toggle) => toggle.setValue(this.plugin.settings.removeSpecialChars).onChange(async (value) => {
      this.plugin.settings.removeSpecialChars = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Apply to Nested Tags").addToggle((toggle) => toggle.setValue(this.plugin.settings.applyToNestedTags).onChange(async (value) => {
      this.plugin.settings.applyToNestedTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Aliases").setHeading();
    containerEl.createEl("p", { text: "Define tag aliases that automatically correct to canonical tags." });
    const aliasesContainer = containerEl.createDiv({ cls: "btm-aliases" });
    this.renderAliases(aliasesContainer);
    new import_obsidian.Setting(containerEl).setName("History").setHeading();
    new import_obsidian.Setting(containerEl).setName("Max History Size").setDesc("Number of operations to keep in history").addSlider((slider) => slider.setLimits(10, 100, 10).setValue(this.plugin.settings.maxHistorySize).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxHistorySize = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Orphan Threshold").setDesc("Tags used fewer times than this are considered orphaned").addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.orphanThreshold).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.orphanThreshold = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Clear History").setDesc("Remove all operation history").addButton((btn) => btn.setButtonText("Clear").setWarning().onClick(async () => {
      this.plugin.settings.operationHistory = [];
      await this.plugin.saveSettings();
      new import_obsidian.Notice("History cleared.");
    }));
  }
  renderAliases(container) {
    container.empty();
    const aliases = this.plugin.settings.aliases;
    for (const [alias, canonical] of Object.entries(aliases)) {
      new import_obsidian.Setting(container).setName(`#${alias} \u2192 #${canonical}`).addButton((btn) => btn.setIcon("trash").setWarning().onClick(async () => {
        delete this.plugin.settings.aliases[alias];
        await this.plugin.saveSettings();
        this.renderAliases(container);
      }));
    }
    const addRow = container.createDiv({ cls: "btm-add-alias" });
    const aliasInput = new import_obsidian.TextComponent(addRow).setPlaceholder("alias");
    const canonicalInput = new import_obsidian.TextComponent(addRow).setPlaceholder("canonical");
    const addBtn = addRow.createEl("button", { text: "Add" });
    addBtn.onclick = async () => {
      const a = aliasInput.getValue().replace(/^#/, "");
      const c = canonicalInput.getValue().replace(/^#/, "");
      if (a && c) {
        this.plugin.settings.aliases[a] = c;
        await this.plugin.saveSettings();
        this.renderAliases(container);
      }
    };
  }
};
